import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as game from '../lib/game.ts';
import * as old from '../lib/game-v3.ts';
import {parseBundle} from '../lib/save-format.ts';
const start=(g=game,s=g.initialState(1000),quest='herbs')=>g.act(s,{type:'start',id:quest},s.updatedAt);
function finish(g,s){let n=0;while(s.squads[0].run&&n++<200000)s=g.settle(s,s.squads[0].run.nextAt).state;assert.ok(n<200000);return s;}
function single(g){return start(g,g.act(g.initialState(1000),{type:'repeat',value:false},1000));}
function bundle(state,format=4){const id=crypto.randomUUID();return {format,deviceId:crypto.randomUUID(),active:id,profiles:[{id,name:'test',test:false,state}],serial:1,sound:false,cloudAt:0,legacyImported:true};}
test('a full first quest is about five times longer without slowing actor clocks',()=>{const a=single(old),b=single(game);assert.equal(b.squads[0].run.nodes,15);assert.deepEqual(b.squads[0].run.actors.map(a=>a.period),a.squads[0].run.actors.map(a=>a.period));const x=finish(old,a),y=finish(game,b),ratio=(y.updatedAt-1000)/(x.updatedAt-1000);assert.ok(ratio>4.5&&ratio<6,`ratio=${ratio}`);assert.equal(y.clears,1);assert.ok(y.gold>=60+32*5);assert.ok(y.wood>=15);});
test('checkpoint rewards survive return without marking an unfinished quest complete',()=>{let s=start();while(s.squads[0].run.node<3)s=game.settle(s,s.squads[0].run.nextAt).state;assert.equal(s.clears,0);assert.ok(s.gold>60);const before=s.gold;s=game.act(s,{type:'stop'},s.updatedAt);assert.equal(s.gold,before);assert.equal(s.clears,0);});
test('20 assists trigger one all-party burst and carry the gauge across nodes',()=>{let s=start();for(let i=0;i<19;i++)s=game.act(s,{type:'assist',mode:'strike'},1000);assert.equal(s.squads[0].run.cheer,95);s=game.act(s,{type:'assist',mode:'strike'},1000);const r=s.squads[0].run;assert.equal(r.cheer,0);assert.equal(r.scene.kind,'burst');assert.deepEqual(new Set(r.events.filter(e=>e.kind==='burst').map(e=>e.hero)),new Set(['aria','leon']));assert.equal(new Set(r.events.map(e=>e.id)).size,r.events.length);});
test('detours finish automatically or earlier when clicked, without duplicate rewards',()=>{let s=start();const d=s.squads[0].run.detour;assert.ok(d);s=game.settle(s,d.at).state;const clicked=game.act(s,{type:'detour'},s.updatedAt);assert.ok(clicked.squads[0].run.detour.finishAt<d.finishAt);const fast=game.settle(clicked,clicked.squads[0].run.detour.finishAt).state;assert.equal(fast.discoveries,1);const auto=game.settle(s,d.finishAt).state;assert.equal(auto.discoveries,1);assert.equal(auto.wood,fast.wood);assert.equal(game.settle(fast,fast.updatedAt).state.discoveries,1);});
test('characters use actual special effects, and an automatic combination crosses node boundaries',()=>{let s=start();const kinds=new Set(),skills=new Set();for(let i=0;i<100;i++){s=game.settle(s,s.squads[0].run.nextAt).state;for(const e of s.squads[0].run.events){kinds.add(e.kind);if(e.kind==='skill')skills.add(e.hero);}}assert.ok(kinds.has('combo'));assert.ok(skills.has('aria'));assert.ok(skills.has('leon'));assert.ok(s.friendship['aria-leon']>0);});
test('higher friendship unlocks stronger linked attacks and new dialogue',()=>{const s=start();const enhanced=structuredClone(s);enhanced.friendship['aria-leon']=24;const a=game.settle(s,15500).state.squads[0].run,b=game.settle(enhanced,15500).state.squads[0].run;assert.notDeepEqual(a.scene.lines,b.scene.lines);assert.match(b.scene.title,/Lv.3/);});
test('building consumes materials once, upgrades real stats, and respects unlocks',()=>{assert.throws(()=>game.act(game.initialState(1000),{type:'build'},1000));let s=game.testState(1000,3,1,1000);s.town=0;const before=game.stats(s,s.squads[0]);s=game.act(s,{type:'build'},1000);assert.equal(s.town,1);assert.equal(s.gold,880);assert.equal(s.wood,33);s.wood=100;s.herbs=100;s.ore=100;s=game.act(s,{type:'build'},1000);assert.equal(s.town,2);assert.ok(game.stats(s,s.squads[0])[0]>before[0]);assert.throws(()=>game.act(s,{type:'build'},1000));});
test('v3 files preserve active quest and resources then start longer next round',()=>{const prior=start(old);const snapshot=structuredClone(prior);const upgraded=parseBundle(bundle(prior,3));const s=upgraded.profiles[0].state;assert.equal(upgraded.format,4);assert.equal(s.version,4);assert.equal(s.squads[0].run.nodes,3);assert.equal(s.squads[0].run.target,prior.squads[0].run.target);assert.deepEqual(prior,snapshot);const later=game.settle(s,40000).state;assert.equal(later.squads[0].run.nodes,15);assert.doesNotThrow(()=>parseBundle(bundle(later)));});
test('offline and small updates produce the same rewards, detours, friendship and timelines',()=>{const s=start(),bulk=game.settle(s,601000).state;let frames=s;for(let now=1100;now<=601000;now+=100)frames=game.settle(frames,now).state;for(const key of ['gold','wood','herbs','ore','xp','clears','friendship','discoveries','squads'])assert.deepEqual(frames[key],bulk[key],key);});
test('offline cap and every transition remain exportable, including rest',()=>{let s=start(game,game.testState(1000,60,1,20000),'dragon');for(let i=0;i<500;i++){s=game.settle(s,s.squads[0].run.nextAt).state;assert.doesNotThrow(()=>parseBundle(bundle(s)));}const result=game.settle(s,s.updatedAt+86400000);assert.equal(result.rewards.capped,true);assert.doesNotThrow(()=>parseBundle(bundle(result.state)));assert.equal(result.rewards.wood,result.state.wood-s.wood);});
test('malformed new timelines and out of range progression are rejected',()=>{for(const mutate of [s=>s.town=3,s=>s.squads[0].run.node=15,s=>s.squads[0].run.cheer=200,s=>s.squads[0].run.comboAt=0]){const s=start();mutate(s);assert.throws(()=>parseBundle(bundle(s)));}});
