'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {Sparkles,Coins,Leaf,Gem,Compass,Users,Flame,BookOpen,CloudCheck,Heart,Swords,Shield,ArrowUpRight,Check,Plus,Pause,Hand,RefreshCw,Download,Upload,Settings,Gift,Hammer} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {heroes,quests,initialState,settle,stats,memberStats,power,level,activeBonds,memberLimit,squadLimit,encounter,targetName,estimate,type State,type Squad,type Action,type Rewards} from '@/lib/game';
const fmt=(n:number)=>Math.floor(n).toLocaleString('ja-JP');
const icons={採取:Leaf,護衛:Shield,討伐:Swords};
const points=[[32,43],[61,65],[79,38]];
type ResponseData={state:State;revision:number;serverNow:number;rewards:Rewards;mode:'guest'|'account';error?:string};
export function Sprite({index,size=72,className=''}:{index:number;size?:number;className?:string}){return <span className={`sprite ${className}`} style={{width:size,height:size,backgroundPosition:`${index%4*100/3}% ${Math.floor(index/4)*50}%`}} aria-hidden="true"/>}
function MapStage({state,squad,now,onAction,ready,startQuest}:{state:State;squad:Squad;now:number;onAction:(a:Action)=>void;ready:boolean;startQuest:string}){
 const run=squad.run,q=quests.find(q=>q.id===run?.quest),node=run?.node||0,point=points[node];let location=[17,52];
 if(run){const from=node===0?[17,52]:[points[node-1][0]-9,points[node-1][1]+4];const to=[point[0]-9,point[1]+4];const progress=run.phase==='move'?Math.min(1,Math.max(0,(now-run.phaseAt)/4000)):1;location=[from[0]+(to[0]-from[0])*progress,from[1]+(to[1]-from[1])*progress];}
 const kind=run&&q?encounter(q,node):null;const lastHit=run?.events.filter(e=>e.kind==='hit'||e.kind==='gather').at(-1);const effects=run?.events.filter(e=>now-e.at>=0&&now-e.at<1200&&e.amount)||[];
 const canHelp=!!run&&run.phase==='work'&&run.energy>0&&ready;
 return <div className="map-shell"><div className="adventure-map" aria-label={run?`${q?.name}の探索マップ`:'森のキャンプ'}><div className="map-vignette"/><div className="map-heading"><span className="eyebrow">{run?'EXPLORING':'A NEW ADVENTURE'}</span><h2>{run?q?.region:'ささやきの森'}</h2><span>{run?`${run.round} 周目 · ${run.phase==='move'?'次の地点へ移動中':run.phase==='rest'?'木陰で休憩中':kind==='battle'?'魔物と戦闘中':kind==='gather'?'素材を採取中':'旅人を護衛中'}`:'ふたりの小さな冒険が、ここから始まる。'}</span></div>
 {run&&q&&<><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="route-line" aria-hidden="true"><polyline points={`17,52 ${points.map(p=>p.join(',')).join(' ')}`} fill="none" stroke="#f4e6b5" strokeWidth=".4" strokeDasharray="1 1.4" opacity=".55"/></svg>{points.map((p,i)=><div key={i} className={`map-node ${i<node?'done':''} ${i===node?'current':''}`} style={{left:`${p[0]}%`,top:`${p[1]}%`}}>{i<node?<span className="node-mark"><Check size={18}/></span>:i>node?<span className="node-mark unknown">?</span>:<><button className={`target ${kind==='battle'?'enemy':''}`} onClick={()=>onAction({type:'assist',squad:squad.id,mode:'strike'})} disabled={!canHelp} aria-label={`${targetName(q,node)}をクリックして手助けする`}><Sprite index={kind==='gather'?11:kind==='escort'?7:q.enemy} size={kind==='battle'?96:78}/></button><div className="target-meter"><span>{targetName(q,node)}</span><Progress value={(kind==='battle'?run.target:run.targetMax-run.target)/run.targetMax*100} aria-label={kind==='battle'?`敵のHP ${run.target} / ${run.targetMax}`:`作業進捗 ${run.targetMax-run.target} / ${run.targetMax}`}/><small>{kind==='battle'?`HP ${run.target} / ${run.targetMax}`:`${Math.round((1-run.target/run.targetMax)*100)}%`}</small></div></>}</div>)}</>}
 {squad.members.map((id,i)=>{const hero=heroes.find(h=>h.id===id)!;const hit=lastHit?.hero===id&&now-lastHit.at<550;return <div key={id} className={`map-hero ${run?.phase==='move'?'walking':''} ${hit?'acting':''} ${run?.phase==='rest'?'resting':''}`} style={{left:`${location[0]+i*5-3}%`,top:`${location[1]+i*6}%`,'--delay':`${i*-.15}s`} as CSSProperties}><Sprite index={hero.sprite} size={84}/><span>{hero.name}<small>Lv.{level(state.xp[id]||0)}</small></span>{hit&&<i className="action-label">{kind==='battle'?'攻撃！':kind==='gather'?'採取中':'護衛中'}</i>}</div>})}
 {effects.map(e=><span key={e.id} className={`damage-number ${e.kind}`} style={{left:`${e.kind==='hurt'||e.kind==='heal'?location[0]+5:point[0]}%`,top:`${e.kind==='hurt'||e.kind==='heal'?location[1]-10:point[1]-17}%`,animationDelay:`-${Math.max(0,now-e.at)}ms`}}>{e.kind==='heal'?'+':e.kind==='gather'?'+':'−'}{e.amount}{e.kind==='assist'?' !':''}</span>)}
 {!run&&<div className="idle-map-note"><Compass size={16}/><span>{quests.find(q=>q.id===startQuest)?.name}</span><button disabled={!ready} onClick={()=>onAction({type:'start',id:startQuest,squad:squad.id})}>出発する<ArrowUpRight size={15}/></button></div>}
 {run&&<div className="party-health"><Heart size={14}/><Progress value={run.hp/run.maxHp*100} aria-label={`パーティHP ${Math.ceil(run.hp)} / ${run.maxHp}`}/><span>{Math.ceil(run.hp)} / {run.maxHp}</span></div>}
 <span className="map-caption">STARLIT GUILD</span></div>
 <div className="assistance"><div><span className="eyebrow">団長の手助け</span><p>{!run?'出発後、マップの敵や素材をクリックできます。':run.phase==='rest'?'回復で今すぐ立て直せます。':kind==='battle'?'敵をクリックして、一撃を加えよう。':'採取や護衛をクリックで手伝おう。'}</p></div><div className="assist-actions"><span className="energy" aria-label={`応援 ${run?.energy||0} / 3`}>{[0,1,2].map(i=><Sparkles key={i} className={run&&i<run.energy?'filled':''} size={16}/>)}</span><button onClick={()=>onAction({type:'assist',squad:squad.id,mode:'strike'})} disabled={!canHelp}><Hand size={15}/>{kind==='battle'?'加勢':'手助け'}</button><button className="outline" disabled={!ready||!run||run.energy<1||run.hp>=run.maxHp} onClick={()=>onAction({type:'assist',squad:squad.id,mode:'heal'})}><Heart size={15}/>回復</button></div><small>応援は8秒で1回分回復。放置中も仲間が自動で行動します。</small></div></div>
}
function SquadCard({squad,selected,onSelect}:{squad:Squad;selected:boolean;onSelect:()=>void}){const q=quests.find(q=>q.id===squad.run?.quest);return <button className={`squad-choice ${selected?'selected':''}`} onClick={onSelect} aria-pressed={selected}><div><b>{squad.name}</b><span>{q?`${q.kind} · ${q.name}`:'キャンプで待機中'}</span></div><div className="tiny-party">{squad.members.map(id=><Sprite key={id} index={heroes.find(h=>h.id===id)!.sprite} size={40}/>)}</div></button>}
export default function Game(){
 const [base,setBase]=useState<State>(initialState(0)),[clock,setClock]=useState(0),[ready,setReady]=useState(false),[mode,setMode]=useState<'guest'|'account'>('guest'),[error,setError]=useState(''),[actionBusy,setActionBusy]=useState(false),[tab,setTab]=useState('adventure'),[selectedSquad,setSelectedSquad]=useState('party-1'),[selectedQuest,setSelectedQuest]=useState('herbs'),[draft,setDraft]=useState<string[]>([]),[saved,setSaved]=useState(0),[report,setReport]=useState<Rewards|null>(null),[saveOpen,setSaveOpen]=useState(false);
 const queue=useRef<Promise<void>>(Promise.resolve()),inFlight=useRef(false),offset=useRef(0),fileInput=useRef<HTMLInputElement>(null),requestCount=useRef(0),alive=useRef(true);
 const sync=useCallback((action?:Action)=>{
  if(!action&&inFlight.current)return;const operationId=action?crypto.randomUUID():undefined;if(action)setActionBusy(true);inFlight.current=true;requestCount.current++;
  queue.current=queue.current.then(async()=>{try{let data:ResponseData|undefined;for(let attempt=0;attempt<2;attempt++){try{const res=await fetch('/api/game',{method:action?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(18000),headers:action?{'Content-Type':'application/json'}:undefined,body:action?JSON.stringify({action,operationId}):undefined});data=await res.json() as ResponseData;if(!res.ok){if(res.status>=500&&attempt===0)continue;throw Object.assign(new Error(data.error||'セーブに接続できません。'),{handled:true});}break;}catch(e){if(attempt===0&&!(e as {handled?:boolean}).handled)continue;throw e;}}
   if(!data||!alive.current)return;offset.current=data.serverNow-Date.now();setClock(data.serverNow);setBase(data.state);setMode(data.mode);setReady(true);setSaved(Date.now());setError('');
   if(data.rewards.count){if(data.rewards.offline)setReport(data.rewards);else toast.success(`${data.rewards.count}件達成！ +${fmt(data.rewards.gold)} G`);}
   if(action&&action.type!=='assist'&&action.type!=='sync')toast.success(action.type==='start'?'冒険へ出発！':action.type==='party'?'編成を保存しました':action.type==='recruit'?'新しい仲間が加わりました':'保存しました');
  }catch(e){if(alive.current){setError((e as Error).message);if(action)toast.error((e as Error).message);}}finally{requestCount.current--;inFlight.current=requestCount.current>0;if(alive.current&&requestCount.current===0)setActionBusy(false);}});
 },[]);
 useEffect(()=>{alive.current=true;const first=setTimeout(()=>sync(),0),poll=setInterval(()=>{if(document.visibilityState==='visible')sync()},20000),frame=setInterval(()=>setClock(Date.now()+offset.current),160);const visible=()=>{if(document.visibilityState==='visible')sync()};document.addEventListener('visibilitychange',visible);return()=>{alive.current=false;clearTimeout(first);clearInterval(poll);clearInterval(frame);document.removeEventListener('visibilitychange',visible);};},[sync]);
 const s=useMemo(()=>ready?settle(base,Math.max(base.updatedAt,clock)).state:base,[base,clock,ready]);const sq=s.squads.find(p=>p.id===selectedSquad)||s.squads[0];const q=quests.find(q=>q.id===selectedQuest)||quests[0];const run=sq.run,activeQuest=quests.find(q=>q.id===run?.quest);const unlocked=quests.filter(q=>q.unlock<=s.clears);const partyStats=stats(s,sq);const synergy=activeBonds(sq.members);const quote=(synergy.length?synergy.flatMap(b=>b.lines):sq.members.map(id=>`${heroes.find(h=>h.id===id)!.name}「${id==='aria'?'風が、こっちだって。':id==='leon'?'焦らず、一歩ずつ行こう。':'次の冒険も、きっと楽しいよ。'}」`))[Math.floor(clock/8000)%Math.max(1,synergy.length?synergy.length*2:sq.members.length)];
 const actionReady=ready&&!actionBusy;const nextRecruit=heroes.find(h=>!s.owned.includes(h.id)&&h.unlock<=s.clears);const nextQuest=quests.find(q=>q.unlock>s.clears);
 function editParty(){setDraft(sq.members);setTab('companions');}
 function chooseSquad(id:string){setSelectedSquad(id);setDraft(s.squads.find(p=>p.id===id)!.members);}
 async function restore(file:File){try{if(file.size>1024)throw Error('復元ファイルを確認してください。');const res=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:await file.text()});const data=await res.json() as {error?:string};if(!res.ok)throw Error(data.error);setSaveOpen(false);setSelectedQuest('herbs');sync();toast.success('ゲストの冒険を復元しました。');}catch(e){toast.error((e as Error).message);}}
 return <main className="shell"><Toaster theme="dark" position="bottom-right"/><header className="masthead"><div className="brand"><Sparkles/><div><h1>星灯りの旅団</h1><small>STARLIT GUILD</small></div></div><div className="resources"><span><Coins/><b>{fmt(s.gold)}</b><small>G</small></span>{(s.herbs>0||s.clears>=3)&&<span><Leaf/><b>{fmt(s.herbs)}</b><small>薬草</small></span>}{(s.ore>0||s.clears>=3)&&<span><Gem/><b>{fmt(s.ore)}</b><small>鉱石</small></span>}</div><Dialog open={saveOpen} onOpenChange={setSaveOpen}><DialogTrigger asChild><button className="save-status"><CloudCheck size={17}/><span>{error?'接続を確認':ready?'自動保存':'読み込み中…'}</span><Settings size={14}/></button></DialogTrigger><DialogContent className="save-dialog"><DialogHeader><DialogTitle>冒険のセーブ</DialogTitle><DialogDescription>{mode==='guest'?'ログインなしのゲストとして遊んでいます。進行はサーバーに保存され、このブラウザーのCookieで続きに戻れます。':'ログイン中のアカウントに紐づけて保存しています。以前の冒険も引き継がれています。'}</DialogDescription></DialogHeader><p className="muted">{saved?`最終確認：${new Date(saved).toLocaleTimeString('ja-JP')}`:'セーブを読み込み中'}</p><button onClick={()=>sync({type:'sync'})} disabled={!ready||actionBusy}><RefreshCw size={16}/>今すぐ保存を確認</button>{mode==='guest'&&<><p>Cookieを消したり、別の端末で遊ぶ場合に備えて、復元ファイルを保管してください。このファイルを持つ人は、あなたの冒険を開けます。</p><a href="/api/save" download="starlit-guild-recovery.json" className="button outline"><Download size={16}/>復元ファイルを保存</a><button className="outline" onClick={()=>fileInput.current?.click()} disabled={actionBusy}><Upload size={16}/>復元ファイルを読み込む</button><input type="file" accept="application/json,.json" ref={fileInput} hidden onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f);e.target.value=''}}/><a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="quiet-link">以前のログイン済みセーブを開く</a></>}<p className="muted">ゲストの冒険とアカウントの冒険は別々です。閉じている間も最大12時間分、自動で進みます。</p></DialogContent></Dialog></header>
 {error&&<div className="notice error" role="alert"><span>{error}</span><button onClick={()=>sync()}><RefreshCw size={15}/>再接続</button></div>}
 {report&&<div className="notice welcome"><Gift/><div><b>おかえりなさい、団長。</b><p>留守の間に {report.count} 件を達成。{fmt(report.gold)} G・薬草 {report.herbs}・鉱石 {report.ore} を獲得しました。{report.capped?'12時間分の冒険を集計しました。':''}</p></div><button className="ghost" onClick={()=>setReport(null)}>確認</button></div>}
 <Tabs value={tab} onValueChange={value=>{if(value==='companions')setDraft(sq.members);setTab(value)}}><div className="nav-row"><TabsList className="game-tabs" variant="line"><TabsTrigger value="adventure"><Compass/>冒険</TabsTrigger>{(s.clears>=3||s.owned.length>2)&&<TabsTrigger value="companions"><Users/>仲間{nextRecruit&&<span className="new-tag">NEW</span>}</TabsTrigger>}{s.clears>=3&&<TabsTrigger value="camp"><Flame/>拠点</TabsTrigger>}{s.clears>0&&<TabsTrigger value="journal"><BookOpen/>記録</TabsTrigger>}</TabsList><span className="chapter-label">{s.clears<10?'ふたりの旅立ち':s.clears<35?'広がる旅路':'星を追う旅団'} <span>· {fmt(s.clears)} 件達成</span></span></div>
 {s.squads.length>1&&<div className="squad-strip">{s.squads.map(p=><SquadCard key={p.id} squad={p} selected={p.id===sq.id} onSelect={()=>chooseSquad(p.id)}/>)}</div>}
 <div className="play-layout"><div className="main-column"><TabsContent value="adventure"><MapStage state={s} squad={sq} now={clock} ready={actionReady} onAction={sync} startQuest={selectedQuest}/><div className="banter"><span>“</span><p>{quote}</p><small>旅のひとこま</small></div><section className="travel-details"><div className="mini-heading"><BookOpen size={16}/><h3>{run?'冒険のできごと':'旅の手引き'}</h3></div>{run?<div className="event-feed">{run.events.slice(-3).reverse().map(e=><p key={e.id}><span>{e.kind==='hurt'?'反撃':e.kind==='heal'?'回復':e.kind==='gather'?'作業':'探索'}</span>{e.text}{e.amount?` ${e.amount}`:''}</p>)}</div>:<p>仲間は自動で歩き、敵と戦い、素材を集めます。出発後はそのまま見守っても、クリックで応援しても。苦戦したら回復や編成で手助けしましょう。</p>}</section></TabsContent>
 <TabsContent value="companions"><div className="section-heading"><div><span className="eyebrow">COMPANIONS</span><h2>旅をともにする仲間</h2></div><span>{s.owned.length} 人</span></div><section className="party-editor"><h3>{sq.name}の編成</h3><p>{run?'冒険中の隊は帰還してから編成できます。':`1〜${Math.max(memberLimit(s),sq.members.length)}人で出発できます。少人数で分担するのも、得意分野を合わせるのも自由。`}</p><div className="draft-summary"><b>{draft.length} 人を選択</b><button disabled={!actionReady||!!run||draft.length<1} onClick={()=>sync({type:'party',squad:sq.id,members:draft})}>この編成を保存</button></div></section><div className="heroes-grid">{heroes.filter(h=>s.owned.includes(h.id)).map(h=>{const selected=draft.includes(h.id),other=s.squads.find(p=>p.id!==sq.id&&p.members.includes(h.id));return <article className={`hero-card ${selected?'picked':''}`} key={h.id}><div className="hero-head"><Sprite index={h.sprite} size={90}/><div><span className="muted">{h.job}</span><h3>{h.name}</h3><small>Lv.{level(s.xp[h.id]||0)} · {h.trait}</small></div></div><p>{h.bio}</p><div className="hero-stats">{['採取','護衛','討伐'].map((name,i)=><span key={name}>{name}<b>{memberStats(s,h.id)[i]}</b></span>)}</div><button className={`outline ${selected?'chosen':''}`} disabled={!actionReady||!!run||!!other||(!selected&&draft.length>=Math.max(memberLimit(s),sq.members.length))} onClick={()=>setDraft(d=>d.includes(h.id)?d.filter(id=>id!==h.id):[...d,h.id])}>{other?`${other.name}に所属`:selected?'編成から外す':'編成に加える'}</button></article>})}</div>{nextRecruit&&<article className="recruit-card"><Sprite index={nextRecruit.sprite} size={100}/><div><span className="eyebrow">新しい出会い</span><h3>{nextRecruit.name}</h3><p>{nextRecruit.job} · {nextRecruit.trait}</p><p>{nextRecruit.bio}</p></div><button disabled={!actionReady||s.gold<nextRecruit.price} onClick={()=>sync({type:'recruit',id:nextRecruit.id})}>{nextRecruit.price} G で迎える</button></article>}{squadLimit(s)>s.squads.length&&<div className="new-squad panel"><div><h3>冒険を、手分けして。</h3><p>待機中の仲間から別の隊を作り、別々の依頼を同時に周回できます。</p></div><button disabled={!actionReady||!s.owned.some(id=>s.squads.every(p=>!p.members.includes(id)))} onClick={()=>sync({type:'newSquad'})}><Plus size={17}/>新しい隊を作る</button></div>}{s.owned.length<4&&<p className="hint">仲間が4人になると、2つの隊に分かれて冒険できます。</p>}</TabsContent>
 <TabsContent value="camp"><div className="section-heading"><div><span className="eyebrow">CAMP & CRAFT</span><h2>次の冒険の支度</h2></div></div><div className="upgrades"><article className="panel upgrade"><Hammer/><h3>みんなの装備 <small>Lv.{s.gear}</small></h3><p>全員の採取・護衛・討伐の力が、1段階ごとに8%増えます。</p><strong>全能力 +{s.gear*8}%</strong><button disabled={!actionReady||s.gear>=15||s.gold<100*(s.gear+1)||s.ore<5*(s.gear+1)} onClick={()=>sync({type:'gear'})}>{s.gear>=15?'最大レベル':`${100*(s.gear+1)} G + 鉱石 ${5*(s.gear+1)} で強化`}</button></article>{s.clears>=10&&<article className="panel upgrade"><Flame/><h3>野営地 <small>Lv.{s.camp}</small></h3><p>仲間の行動間隔が、1段階ごとに3.5%短くなります。</p><strong>行動間隔 −{Math.round(s.camp*3.5*10)/10}%</strong><button disabled={!actionReady||s.camp>=10||s.gold<150*(s.camp+1)||s.herbs<12*(s.camp+1)} onClick={()=>sync({type:'camp'})}>{s.camp>=10?'最大レベル':`${150*(s.camp+1)} G + 薬草 ${12*(s.camp+1)} で改築`}</button></article>}</div><article className="panel daily"><Gift/><div><h3>ギルドの差し入れ</h3><p>80 G と薬草 5 個。毎朝9時に届きます。</p></div><button disabled={!actionReady||s.lastDaily===new Date(clock||0).toISOString().slice(0,10)} onClick={()=>sync({type:'daily'})}>{s.lastDaily===new Date(clock||0).toISOString().slice(0,10)?'受取済み':'受け取る'}</button></article></TabsContent>
 <TabsContent value="journal"><div className="section-heading"><div><span className="eyebrow">OUR STORY</span><h2>旅団の足あと</h2></div><span>{fmt(s.clears)} 件達成</span></div><div className="journal">{s.log.map((e,i)=><article key={`${e.at}-${i}`}><time>{e.at?new Date(e.at).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}):'旅立ちの日'}</time><p>{e.text}</p></article>)}</div><h3 className="subheading">見つけた依頼</h3><div className="collection">{unlocked.map(q=><div key={q.id}><span>{q.name}</span><b>{s.done[q.id]||0} 回達成</b></div>)}</div>{s.done.dragon>0&&<div className="ending"><Sparkles/><h3>星の灯りは、ふたたび。</h3><p>古塔に星の灯りが戻った。けれど、旅団の物語はまだ続く。</p></div>}</TabsContent></div>
 <aside className="side-column"><section className="panel party-panel"><div className="panel-title"><h2>{sq.name}</h2><span>{run?'冒険中':'待機中'}</span></div><div className="party-members">{sq.members.map(id=>{const h=heroes.find(h=>h.id===id)!;return <div className="member" key={id}><Sprite index={h.sprite} size={57}/><div><b>{h.name}</b><small>{h.job}</small></div><span className="level">Lv.{level(s.xp[id]||0)}</span></div>})}</div><div className="stat-bars">{['採取','護衛','討伐'].map((name,i)=>{const Icon=icons[name as keyof typeof icons];return <div key={name}><span><Icon size={14}/>{name}</span><b>{partyStats[i]}</b></div>})}</div>{synergy.map(b=><div className="synergy" key={b.name}><Heart size={14}/><span>{b.name}<small>全能力 +{b.bonus}</small></span></div>)}{(s.clears>=3||s.owned.length>2)&&<button className="outline full" onClick={editParty}><Users size={15}/>編成する</button>}{run&&<><label className="switch-row"><span>クリア後に自動周回</span><Switch checked={sq.repeat} onCheckedChange={value=>sync({type:'repeat',squad:sq.id,value})} disabled={!actionReady} aria-label="クリア後に自動周回"/></label><AlertDialog><AlertDialogTrigger asChild><button className="quiet full" disabled={!actionReady}><Pause size={14}/>この隊を帰還させる</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{sq.name}を帰還させますか？</AlertDialogTitle><AlertDialogDescription>達成済みの報酬は残ります。途中の依頼は初めからになります。いまの1周を終えて帰る場合は、自動周回をオフにしてください。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>冒険を続ける</AlertDialogCancel><AlertDialogAction onClick={()=>sync({type:'stop',squad:sq.id})}>帰還する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>}</section>
 <section className="quest-board"><div className="section-heading"><div><span className="eyebrow">QUEST BOARD</span><h2>届いた依頼</h2></div><small>{unlocked.length} 件</small></div>{unlocked.map(quest=>{const Icon=icons[quest.kind],chosen=quest.id===selectedQuest;return <button className={`quest-card ${chosen?'selected':''}`} key={quest.id} aria-pressed={chosen} onClick={()=>{setSelectedQuest(quest.id);setTab('adventure')}}><div className="quest-top"><span><Icon size={14}/>{quest.kind}</span><small>{Math.max(1,Math.round(estimate(s,sq,quest)/60))}分ほど</small></div><h3>{quest.name}</h3><div className="quest-meta"><span><Coins size={13}/>{quest.gold} G</span><span>EXP {quest.xp}</span></div></button>})}<div className="quest-detail"><p>{q.desc}</p><div className="aptitude"><span>{q.kind}の目安 <b>{q.need}</b></span><span className={power(s,sq,q)>=q.need?'fit':'caution'}>{power(s,sq,q)>=q.need?'得意な依頼':'手助けがあると安心'}</span></div><p className="reward-line">薬草 {q.herbs} · 鉱石 {q.ore} · 仲間それぞれに EXP {q.xp}</p><button className="full start-button" disabled={!actionReady||!!run} onClick={()=>sync({type:'start',id:q.id,squad:sq.id})}>{run?`${activeQuest?.name}を冒険中`:'この依頼へ出発'}{!run&&<ArrowUpRight size={17}/>}</button><small>能力は目安です。届かなくても挑戦できます。</small></div>{nextQuest&&<p className="discovery-hint"><Compass size={15}/>あと {nextQuest.unlock-s.clears} 件の冒険で、新しい依頼が届きます。</p>}</section></aside></div></Tabs><footer><span>STARLIT GUILD · 星灯りの旅団</span><span><CloudCheck size={13}/>{mode==='guest'?'ゲストの冒険を自動保存':'アカウントに自動保存'} · オフライン最大12時間</span></footer></main>
}

