'use client';
import { useState,useEffect,useRef,useCallback } from 'react';
import { Compass,Sparkles,Coins,Leaf,Gem,Shield,Swords,Users,Flame,BookOpen,CloudCheck,RefreshCw,Clock,ArrowUpRight,Lock,Gift,Check,ChevronRight,Heart,Flag,Hammer,Pause,Star } from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {heroes,quests,initialState,stats,power,level,activeBonds,guildRank,duration,rewardGold,achievements,type State,type Action,type Quest} from '@/lib/game';
const kindIcons={採取:Leaf,護衛:Shield,討伐:Swords};
type GameResponse={state:State;revision:number;serverNow:number;error?:string;signIn?:boolean;conflict?:boolean;rewards:{count:number;gold:number;xp:number;offline:boolean;capped:boolean}};
const fmt=(v:number)=>v.toLocaleString('ja-JP');
const time=(ms:number)=>{const s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
function Emblem({id,small=false}:{id:string;small?:boolean}){const h=heroes.find(h=>h.id===id)!;return <span className={`emblem ${small?'small':''}`} style={{color:h.color,borderColor:h.color+'77',background:h.color+'16'}} aria-hidden="true">{h.mark}</span>}
function QuestCard({quest,s,selected,onSelect}:{quest:Quest;s:State;selected:string;onSelect:(id:string)=>void}){const Icon=kindIcons[quest.kind],locked=quest.tier>guildRank(s),ok=power(s,quest)>=quest.need;return <button className={`quest-card ${selected===quest.id?'selected':''} ${locked?'locked':''}`} onClick={()=>onSelect(quest.id)} aria-pressed={selected===quest.id}><div className={`quest-icon ${quest.kind}`}><Icon size={25}/></div><div className="quest-main"><div className="quest-top"><span className="tag">{quest.kind}</span><span className="muted">{quest.region}</span></div><h3>{quest.name}</h3><p>{quest.desc}</p><div className="quest-meta"><span><Clock size={13}/>{Math.round(duration(s,quest)/60000*10)/10}分</span><span><Coins size={13}/>{rewardGold(s,quest)} G</span><span>EXP {quest.xp}</span></div></div><div className="quest-fit">{locked?<><Lock size={16}/><span>ランク {quest.tier}</span></>:<><span className={ok?'fit':'unfit'}>{ok?'達成可能':'能力不足'}</span><span>{power(s,quest)} / {quest.need}</span></>}<ChevronRight size={18}/></div></button>}
export default function Game(){
 const [s,setS]=useState<State>(initialState(0));const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [signIn,setSignIn]=useState(false);const [tab,setTab]=useState('quests');const [filter,setFilter]=useState('すべて');const [selected,setSelected]=useState('herbs');const [draft,setDraft]=useState<string[]>(['aria','leon','mira']);const [tick,setTick]=useState(0);const [clock,setClock]=useState(0);const [saved,setSaved]=useState(0);const [returnReport,setReturnReport]=useState<{count:number;gold:number;xp:number;capped:boolean}|null>(null);
 const rev=useRef(0),pending=useRef(false),offset=useRef(0),init=useRef(false);
 const refresh=useCallback(async(action?:Action)=>{
  if(pending.current)return;pending.current=true;setBusy(true);
  try{const res=await fetch('/api/game',{method:action?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(15000),headers:action?{'Content-Type':'application/json'}:undefined,body:action?JSON.stringify({action,revision:rev.current}):undefined});const data=await res.json() as GameResponse;if(!res.ok){if(data.signIn)setSignIn(true);if(data.conflict){setError(data.error||'冒険を更新してから、もう一度操作してください。');return;}throw Error(data.error||'接続できませんでした。');}
   rev.current=data.revision;offset.current=data.serverNow-Date.now();setClock(data.serverNow);setS(data.state);setReady(true);setSignIn(false);setError('');setSaved(Date.now());
   if(!init.current){setDraft(data.state.party);init.current=true;}
   if(data.rewards.count){if(data.rewards.offline)setReturnReport(data.rewards);else toast.success(`${data.rewards.count}件達成！ +${fmt(data.rewards.gold)} G`,{description:`仲間それぞれに経験値 +${data.rewards.xp}`});}
   if(action&&action.type!=='sync')toast.success(action.type==='start'?'旅団が冒険へ出発しました':action.type==='party'?'パーティを保存しました':'保存しました');
  }catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}
 },[]);
 useEffect(()=>{const first=setTimeout(()=>void refresh(),0);const poll=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);const frame=setInterval(()=>{setClock(Date.now()+offset.current);setTick(t=>t+1)},1000);const visible=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(first);clearInterval(poll);clearInterval(frame);document.removeEventListener('visibilitychange',visible);};},[refresh]);
 const q=quests.find(q=>q.id===(s.active?.quest||selected))!;const rank=guildRank(s);const partyStats=stats(s);const synergy=activeBonds(s);const progress=s.active?Math.min(100,Math.max(0,(clock-s.active.started)/s.active.duration*100)):0;const available=ready&&!busy&&!error;const durationLeft=s.active?s.active.started+s.active.duration-clock:0;const started=s.active!==null;
 const sayings=synergy.length?synergy.flatMap(b=>b.lines):s.party.map(id=>{const h=heroes.find(h=>h.id===id)!;return `${h.name}「${({aria:'葉っぱの下も探してみよう。',leon:'みんな、足元に気をつけて。',mira:'ひと休みしたら、お茶にしましょう。',finn:'お宝の気配がする！',garr:'後ろは俺に任せてくれ。',luna:'今夜の星は、いつもより近いね。',poppy:'新しいレシピを思いついたよ！',noel:'この景色を、歌に残そう。'} as Record<string,string>)[id]}」`;});
 const quote=sayings[Math.floor(tick/8)%sayings.length];
 const candidate={...s,party:draft};const candidateStats=stats(candidate);
 function pick(id:string){setDraft(d=>d.includes(id)?d.filter(x=>x!==id):d.length<3?[...d,id]:d);}


 return <main className="shell"><Toaster theme="dark" position="bottom-right"/><header className="masthead"><div className="brand"><Sparkles/><div><h1>星灯りの旅団</h1><small>THE STARLIT GUILD</small></div></div><div className="resources" aria-label="所持資源"><span title="お金"><Coins/><b>{fmt(s.gold)}</b><small>G</small></span><span title="薬草"><Leaf/><b>{fmt(s.herbs)}</b><small>薬草</small></span><span title="鉱石"><Gem/><b>{fmt(s.ore)}</b><small>鉱石</small></span></div><button className="save-status" onClick={()=>refresh({type:'sync'})} disabled={busy||signIn} title="今すぐ同期"><CloudCheck size={17}/><span>{busy?'同期中…':error?'再接続':ready?'保存済み':'接続中…'}</span></button></header>
 {error&&<div className="notice error" role="alert"><span>{error}</span>{signIn?<a className="button" href="/signin-with-chatgpt?return_to=%2F" target="_top">ログインして冒険を始める</a>:<button onClick={()=>refresh()} disabled={busy}><RefreshCw size={16}/>再接続</button>}</div>}
 {returnReport&&<section className="notice welcome"><Gift/><div><b>おかえりなさい、団長。</b><p>留守の間に {returnReport.count} 件を達成。{fmt(returnReport.gold)} G と経験値 {fmt(returnReport.xp)} を獲得しました。{returnReport.capped?'12時間分の冒険を集計しました。':''}</p></div><button className="ghost" onClick={()=>setReturnReport(null)}>確認</button></section>}
 <Tabs value={tab} onValueChange={setTab}><div className="nav-row"><TabsList className="game-tabs" variant="line"><TabsTrigger value="quests"><Compass/>冒険</TabsTrigger><TabsTrigger value="party"><Users/>仲間</TabsTrigger><TabsTrigger value="camp"><Flame/>ギルド</TabsTrigger><TabsTrigger value="journal"><BookOpen/>冒険の記録</TabsTrigger></TabsList><span className="rank"><Flag size={14}/>旅団ランク <b>{rank}</b><span className="rank-name">{['','駆け出し','一人前','星の旅人'][rank]}</span></span></div>
 <div className="game-layout"><div className="main-column"><section className={`stage ${started?'traveling':''}`} aria-label="冒険の様子"><div className="stage-copy"><span className="eyebrow">{started?'ON AN ADVENTURE':'CHAPTER 0'+rank} · {started?q.region:['','はじまりの森','銀霧の渓谷','星灯りの古塔'][rank]}</span><h2>{started?q.name:<>小さな旅が、<br/>物語になる。</>}</h2><p>{started?'仲間に任せて、ゆっくり待とう。':'仲間と依頼を選んで、次の冒険へ。'}</p>{!started&&<button disabled={!available||q.tier>rank||power(s,q)<q.need} onClick={()=>refresh({type:'start',id:q.id})}><Compass size={17}/>{q.tier>rank?'旅団ランクが足りません':power(s,q)<q.need?'パーティの能力が足りません':'この依頼に出発'}<ArrowUpRight size={16}/></button>}{!started&&<div className="chosen-quest">選択中：{q.name}</div>}</div><div className="stage-corner"><Sparkles size={14}/> 星灯りの世界</div>{started&&<div className="adventure-progress"><div><span className="travel-status"><span className="pulse"/> {progress<33?'目的地へ移動中':progress<75?'依頼を遂行中':'帰路についています'}</span><b>{durationLeft<=0?'報酬を集計中…':`あと ${time(durationLeft)}`}</b></div><Progress value={progress} aria-label="現在のクエストの進行"/></div>}</section>
 <div className="banter"><span className="quote-icon">“</span><p key={quote}>{quote}</p><small>{started?'旅のひとこま':'ギルドのひとこま'}</small></div>
 <TabsContent value="quests"><section className="board"><div className="section-heading"><div><span className="eyebrow">QUEST BOARD</span><h2>クエスト掲示板</h2></div><span className="muted">{quests.filter(q=>q.tier<=rank).length} 件の依頼を受注可能</span></div><div className="filter-row" aria-label="クエストの種類">{['すべて','採取','護衛','討伐'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<span>3人の得意分野と相性が、冒険の鍵。</span></div><div className="quest-list">{quests.filter(q=>filter==='すべて'||q.kind===filter).map(quest=><QuestCard key={quest.id} quest={quest} s={s} selected={selected} onSelect={setSelected}/>)}</div><div className="selected-detail"><div><b>{q.name}</b><p>{q.kind}能力 {q.need} 以上で確実に達成。<br/>報酬：{rewardGold(s,q)} G・各人 EXP {q.xp}・薬草 {q.herbs}・鉱石 {q.ore}</p></div><button disabled={!available||started||q.tier>rank||power(s,q)<q.need} onClick={()=>refresh({type:'start',id:q.id})}>{started?'冒険中':'出発する'}<ArrowUpRight size={17}/></button></div></section></TabsContent>
 <TabsContent value="party"><section className="board"><div className="section-heading"><div><span className="eyebrow">YOUR COMPANIONS</span><h2>旅をともにする仲間</h2></div><span className="muted">{s.owned.length} / {heroes.length} 人</span></div><div className="party-editor"><p>{started?'帰還すると編成を変更できます。':'出発する仲間を3人選んでください。枠がいっぱいのときは、先に1人外します。'}</p><div className="draft-summary"><span>{draft.length} / 3 人</span><span>採取 {candidateStats[0]}・護衛 {candidateStats[1]}・討伐 {candidateStats[2]}</span><button disabled={!available||started||draft.length!==3} onClick={()=>refresh({type:'party',party:draft})}>編成を保存</button></div>{activeBonds(candidate).length>0&&<p className="bond-preview">発動する絆：{activeBonds(candidate).map(b=>`${b.name} +${b.bonus}`).join(' / ')}</p>}</div><div className="heroes-grid">{heroes.map(h=>{const owned=s.owned.includes(h.id),picked=draft.includes(h.id);return <article key={h.id} className={`hero-card ${picked?'picked':''}`}><div className="hero-head"><Emblem id={h.id}/><div><span className="muted">{h.job}</span><h3>{h.name} <small>Lv.{level(s.xp[h.id]||0)}</small></h3></div>{picked&&<Check className="hero-check" size={18}/>}</div><p>{h.bio}</p><span className="trait">{h.trait}</span><div className="hero-stats">{['採取','護衛','討伐'].map((name,i)=><span key={name}>{name}<b>{Math.floor(h.stats[i]*(1+.1*(level(s.xp[h.id]||0)-1)))}</b></span>)}</div>{owned?<><Progress value={level(s.xp[h.id]||0)===50?100:((s.xp[h.id]||0)-30*(level(s.xp[h.id]||0)-1)**2)/(30*(2*level(s.xp[h.id]||0)-1))*100} aria-label={`${h.name}の経験値`}/><small className="xp-label">累計 EXP {fmt(s.xp[h.id]||0)} · 冒険でレベルアップ</small><button className={picked?'outline chosen':'outline'} disabled={!available||started||(!picked&&draft.length>=3)} onClick={()=>pick(h.id)}>{picked?'編成から外す':'パーティに選ぶ'}</button></>:<button className="recruit" disabled={!available||s.gold<h.price} onClick={()=>refresh({type:'recruit',id:h.id})}><Users size={15}/>{fmt(h.price)} G で仲間にする</button>}</article>})}</div></section></TabsContent>
 <TabsContent value="camp"><section className="board"><div className="section-heading"><div><span className="eyebrow">GUILD & CRAFT</span><h2>冒険の支度</h2></div><span className="muted">旅団みんなの成長に</span></div><div className="upgrades"><article className="upgrade panel"><Hammer/><h3>旅団の装備 <small>Lv.{s.gear} / 15</small></h3><p>1段階ごとに、パーティの全能力 +8%。</p><strong>現在 +{s.gear*8}%</strong><button disabled={!available||s.gear>=15||s.gold<120*(s.gear+1)||s.ore<8*(s.gear+1)} onClick={()=>refresh({type:'gear'})}>{s.gear>=15?'最大レベル':`${120*(s.gear+1)} G + 鉱石 ${8*(s.gear+1)} で強化`}</button></article><article className="upgrade panel"><Flame/><h3>野営地 <small>Lv.{s.camp} / 10</small></h3><p>1段階ごとに、次の周回から所要時間 −4%。</p><strong>現在 −{s.camp*4}%</strong><button disabled={!available||s.camp>=10||s.gold<150*(s.camp+1)||s.herbs<12*(s.camp+1)} onClick={()=>refresh({type:'camp'})}>{s.camp>=10?'最大レベル':`${150*(s.camp+1)} G + 薬草 ${12*(s.camp+1)} で改築`}</button></article></div><article className="daily panel"><Gift/><div><h3>ギルドの差し入れ</h3><p>毎日 80 G と薬草 5 個。日本時間の朝9時に更新。</p></div><button disabled={!available||s.lastDaily===new Date(clock||0).toISOString().slice(0,10)} onClick={()=>refresh({type:'daily'})}>{s.lastDaily===new Date(clock||0).toISOString().slice(0,10)?'受取済み':'受け取る'}</button></article><h3 className="subheading">旅団の実績</h3><div className="achievement-list">{achievements.map(a=><article key={a.id} className="achievement"><Star/><div><h3>{a.name}</h3><p>{a.desc} · {Math.min(s.clears,a.need)} / {a.need}</p></div><span className="gold">{fmt(a.gold)} G</span><button className="outline" disabled={!available||s.clears<a.need||s.claimed.includes(a.id)} onClick={()=>refresh({type:'claim',id:a.id})}>{s.claimed.includes(a.id)?'受取済み':'受け取る'}</button></article>)}</div></section></TabsContent>
 <TabsContent value="journal"><section className="board"><div className="section-heading"><div><span className="eyebrow">ADVENTURE JOURNAL</span><h2>冒険の記録</h2></div><span className="muted">累計 {fmt(s.clears)} 件達成</span></div><div className="journal">{s.log.map((entry,i)=><article key={`${entry.at}-${i}`}><span className="journal-dot"/><time>{entry.at?new Date(entry.at).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}):'旅立ちの日'}</time><p>{entry.text}</p></article>)}</div><h3 className="subheading">クエスト図鑑</h3><div className="collection">{quests.map(q=><div key={q.id}><span>{s.done[q.id]?<Check size={16}/>:<Lock size={16}/>}</span><p>{q.name}</p><b>{s.done[q.id]||0} 回</b></div>)}</div>{s.done.dragon>0&&<div className="ending"><Sparkles/><h3>星の灯りは、ふたたび。</h3><p>古塔に灯りが戻り、谷の人々に笑顔が戻った。<br/>けれど旅団の物語は、まだ終わらない。次の冒険へ出かけよう。</p></div>}</section></TabsContent>
 </div><aside className="side-column"><section className="panel party-panel"><div className="panel-title"><h2>冒険パーティ</h2><span>3 / 3</span></div><div className="party-members">{s.party.map((id,i)=>{const h=heroes.find(h=>h.id===id)!;return <div className="member" key={id}><span className="member-no">0{i+1}</span><Emblem id={id} small/><div><b>{h.name}</b><small>{h.job}</small></div><span className="level">Lv.{level(s.xp[id]||0)}</span></div>})}</div><div className="stat-bars">{['採取','護衛','討伐'].map((label,i)=>{const Icon=kindIcons[label as keyof typeof kindIcons];return <div key={label}><span><Icon size={14}/>{label}</span><Progress value={Math.min(100,partyStats[i]/250*100)} aria-label={`${label}能力 ${partyStats[i]}`}/><b>{partyStats[i]}</b></div>})}</div>{synergy.map(b=><div className="synergy" key={b.name}><Heart size={15}/><div><b>{b.name}</b><span>全能力 +{b.bonus}</span></div></div>)}<button className="outline full" onClick={()=>{setDraft(s.party);setTab('party');}}>パーティを編成<Users size={15}/></button></section>
 <section className="panel expedition-panel"><div className="panel-title"><h2>冒険の設定</h2><Compass size={19}/></div><label className="switch-row"><span>同じ依頼を自動周回</span><Switch checked={s.repeat} onCheckedChange={value=>refresh({type:'repeat',value})} disabled={!available} aria-label="同じ依頼を自動周回"/></label><p>画面を閉じても最大12時間分の冒険が進みます。報酬は自動で受け取ります。</p>{started&&<AlertDialog><AlertDialogTrigger asChild><button className="outline full" disabled={!available}><Pause size={15}/>冒険を切り上げる</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>ギルドへ帰還しますか？</AlertDialogTitle><AlertDialogDescription>達成済みの報酬はそのまま残ります。現在進行中の依頼の進捗は失われます。1周を終えて止めたい場合は、自動周回をオフにしてください。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>冒険を続ける</AlertDialogCancel><AlertDialogAction onClick={()=>refresh({type:'stop'})}>帰還する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</section>
 <section className="guild-goal"><span className="eyebrow">NEXT MILESTONE</span><h3>{rank===3?'星喰い竜に挑もう':rank===2?'星の旅人を目指して':'まずは10件の冒険を'}</h3><p>{rank===3?'仲間と装備を育て、古塔に星の灯りを取り戻そう。':`${rank===1?'10':'40'}件の達成で、次の地域の依頼が解放されます。`}</p><Progress value={rank===3?Math.min(100,power(s,quests[8])/210*100):s.clears/(rank===1?10:40)*100} aria-label="次の目標への進捗"/><small>{rank===3?`討伐能力 ${power(s,quests[8])} / 210`:`達成数 ${s.clears} / ${rank===1?10:40}`}</small></section>
 <section className="howto"><BookOpen size={17}/><div><h3>冒険の手引き</h3><p>依頼を選ぶ → 出発 → 報酬で育成。能力が条件を満たせば確実にクリアできます。仲間のレベル上限は50です。</p></div></section></aside></div></Tabs><footer><span>星灯りの旅団</span><span><CloudCheck size={13}/>{ready?`クラウドセーブ · ${saved?new Date(saved).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):''}`:'クラウドに接続中'} · オフライン進行 最大12時間</span></footer></main>
}



