'use client';
import {Fragment,type CSSProperties} from 'react';
import {Sparkles,Compass,Heart,ArrowUpRight,Check} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Sprite} from './sprite';
import {AttackTrail,BattleEffects,BurstScene,DiscoveryArt} from './battle-effects';
import {heroes,allQuests as quests,heroSkills,travelMs,encounter,targetName,type State,type Squad,type Action} from '@/lib/game';
const points=[[32,43],[61,65],[79,38]];
export function MapStage({state,squad,now,onAction,ready,startQuest}:{state:State;squad:Squad;now:number;onAction:(a:Action)=>void;ready:boolean;startQuest:string}){
 const run=squad.run,q=quests.find(q=>q.id===(run?.quest||startQuest)),node=run?.node||0,localNode=node%3,point=points[localNode];const location=run?[point[0]-12,point[1]+4]:[17,52];
 const background=q?.background||(q?.id==='crystal'?'/cave.png':q?.id==='dragon'?'/ruins.png':['pilgrim','wolf','royal'].includes(q?.id||'')?'/valley.png':'/forest.png');
 const kind=run&&q?encounter(q,node):null;const effects=run?.events.filter(e=>now-e.at>=0&&now-e.at<1200&&e.amount&&e.id.startsWith(`${run.round}-${run.node}-`))||[];
 const canHeal=!!run&&ready&&(run.hp<run.maxHp||run.phase==='rest');
 const help=()=>onAction({type:'assist',squad:squad.id,mode:run?.phase==='rest'?'heal':'strike'});
 const heal=()=>onAction({type:'assist',squad:squad.id,mode:'heal'});
 return <div className="map-shell"><div className="adventure-map" style={{backgroundImage:`url(${background})`}} aria-label={run?`${q?.name}の探索マップ`:'森のキャンプ'}>{run&&<button className="map-tap-surface" onClick={help} disabled={!ready} aria-label={run.phase==='rest'?'マップをタップしてパーティを回復':'マップをタップして手助け'}/>}<div className="map-vignette"/><div className="map-heading"><span className="eyebrow">{run?'EXPLORING':'A NEW ADVENTURE'}</span><h2>{q?.region||'ささやきの森'}</h2><span>{run?`${run.round} 周目 · 地点 ${node+1}/${run.nodes} · ${run.phase==='move'?'次の地点へ移動中':run.phase==='rest'?'木陰で休憩中':kind==='battle'?'魔物と戦闘中':kind==='gather'?'素材を採取中':'旅人を護衛中'}`:(state.clears===0&&squad.members.includes('aria')&&squad.members.includes('leon')?'ふたりの小さな冒険が、ここから始まる。':'支度ができたら、次の冒険へ。')}</span></div>
 {run&&q&&<><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="route-line" aria-hidden="true"><polyline points={`17,52 ${points.map(p=>p.join(',')).join(' ')}`} fill="none" stroke="#f4e6b5" strokeWidth=".4" strokeDasharray="1 1.4" opacity=".55"/></svg>{points.map((p,i)=><div key={i} className={`map-node ${i<localNode?'done':''} ${i===localNode?'current':''}`} style={{left:`${p[0]}%`,top:`${p[1]}%`}}>{i<localNode?<span className="node-mark"><Check size={18}/></span>:i>localNode?<span className="node-mark unknown">?</span>:<><button className={`target ${kind==='battle'?'enemy':''} ${run.events.some(e=>e.kind==='hurt'&&now-e.at<320)?'striking':''} ${run.events.some(e=>(e.kind==='hit'||e.kind==='assist')&&now-e.at<180)?'damaged':''}`} onClick={help} disabled={!ready} aria-label={run.phase==='rest'?'タップしてパーティを回復':`${targetName(q,node)}をタップして手助けする`}><Sprite index={kind==='gather'?11:kind==='escort'?7:q.enemy} size={kind==='battle'?96:78}/></button><div className="target-meter"><Progress value={(kind==='battle'?run.target:run.targetMax-run.target)/run.targetMax*100} aria-label={kind==='battle'?`敵のHP ${run.target} / ${run.targetMax}`:`作業進捗 ${run.targetMax-run.target} / ${run.targetMax}`}/></div></>}</div>)}</>}
 {q?.companion&&run&&<div className="quest-guest" role="img" aria-label={heroes.find(h=>h.id===q.companion)!.name+'が同行中'}><Sprite index={heroes.find(h=>h.id===q.companion)!.sprite} size={48}/></div>}
 {squad.members.map((id,i)=>{const hero=heroes.find(h=>h.id===id)!;const lastHit=run?.events.filter(e=>e.id.startsWith(`${run.round}-${run.node}-`)&&e.hero===id&&(['hit','gather','skill','burst'].includes(e.kind))).at(-1);const hit=!!lastHit&&now>=lastHit.at&&now-lastHit.at<650;const actor=run?.actors.find(a=>a.hero===id);const walking=!!run&&run.phase!=='rest'&&now<(actor?.arrivesAt||0);
 const from=localNode===0?[17+i*5,52+i*6]:[points[localNode-1][0]-14+i*4,points[localNode-1][1]+i*5];
 const style=heroSkills[id].style,front=['melee','tank','rogue'].includes(style);const to=[point[0]-(front?9:23)+i*2,point[1]+3+i*6];const progress=run?Math.max(0,Math.min(1,(now-run.phaseAt)/travelMs(id))):0;
 const cycle=actor?Math.max(0,now-actor.arrivesAt)/actor.period:0;const roam=run&&!walking&&run.phase!=='rest';
 let x=run?from[0]+(to[0]-from[0])*progress+(roam?Math.sin(cycle*Math.PI*2)*1.4+(hit?2:0):0):17+i*5;
 let y=run?from[1]+(to[1]-from[1])*progress+(roam?Math.cos(cycle*Math.PI*2+i)*1.5:0):52+i*6;
 const detour=run?.detour;const exploring=!!detour&&detour.hero===id&&!detour.claimed&&now>=detour.at;
 if(exploring&&detour){const progress=Math.min(1,Math.max(0,(now-detour.at)/1400));x=x+(Math.max(20,point[0]-18)-x)*progress;y=y+(Math.min(75,point[1]+25)-y)*progress;}
 const projectile=hit&&!exploring&&['ranged','mage','bard','healer'].includes(style)&&kind==='battle';
 return <Fragment key={id}>{projectile&&lastHit&&<AttackTrail key={lastHit.id} event={lastHit} now={now} style={style} from={[x,y]} to={point}/>}<div className={`map-hero role-${style} ${exploring?'exploring':''} ${walking?'walking':''} ${hit&&!exploring?'acting':''} ${run?.phase==='rest'?'resting':''}`} style={{left:`${x}%`,top:`${y}%`,'--shot-distance':(point[0]-x)+'cqw','--delay':`${i*-.15}s`} as CSSProperties}>{run&&<button className="hero-heal-target" onClick={heal} disabled={!canHeal} aria-label={`${hero.name}をタップしてパーティを回復`}/>}<Sprite index={hero.sprite} size={84}/>{run&&i===0&&<button className="party-health" onClick={heal} disabled={!canHeal} aria-label="HPをタップしてパーティを回復"><Heart size={9}/><Progress value={run.hp/run.maxHp*100} aria-label={`隊全体のHP ${Math.ceil(run.hp)} / ${run.maxHp}`}/></button>}{exploring&&<i className="action-label">寄り道中</i>}{hit&&!exploring&&<i key={lastHit?.id} className="action-label">{lastHit?.kind==='skill'?heroSkills[id].name:lastHit?.kind==='burst'?'必殺！':kind==='battle'?'攻撃！':kind==='gather'?'採取中':'護衛中'}</i>}</div></Fragment>})}
 {run?.detour&&now>=run.detour.at&&(!run.detour.claimed||now-run.detour.finishAt<1000)&&<button className={`detour-target ${run.detour.claimed?'claimed':''}`} style={{left:`${Math.max(20,point[0]-18)}%`,top:`${Math.min(75,point[1]+25)}%`,'--claim-age':`${-Math.max(0,now-run.detour.finishAt)}ms`} as CSSProperties} onClick={()=>onAction({type:'detour',squad:squad.id})} disabled={!ready||run.detour.claimed||run.phase==='rest'} aria-label="寄り道を優先して調べる"><DiscoveryArt key={`${run.detour.at}-${run.detour.claimed}`} kind={run.detour.kind} claimed={run.detour.claimed} now={now} finishAt={run.detour.finishAt}/><span>{run.detour.claimed?'見つけた！':run.detour.kind==='chest'?'隠し宝箱':run.detour.kind==='herb'?'光る草むら':'迷子の精霊'}</span><small>{run.detour.claimed?'': 'タップで優先探索'}</small></button>}
 {run&&<><BattleEffects run={run} now={now} point={point} location={location} battle={kind==='battle'}/><BurstScene run={run} members={squad.members} now={now}/></>}
 {effects.map((e,i)=><span key={e.id} className={`damage-number ${e.kind}`} style={{left:`${e.kind==='hurt'||e.kind==='heal'?location[0]+5:point[0]+(i%4-1.5)*2}%`,top:`${e.kind==='hurt'||e.kind==='heal'?location[1]-10:point[1]-17}%`,animationDelay:`-${Math.max(0,now-e.at)}ms`}}>{e.kind==='heal'||e.kind==='gather'||e.kind==='assist'&&kind!=='battle'?'+':'−'}{e.amount}{['assist','burst','combo'].includes(e.kind)?' !':''}</span>)}
 {!run&&<div className="idle-map-note"><Compass size={16}/><span>{quests.find(q=>q.id===startQuest)?.name}</span><button disabled={!ready} onClick={()=>onAction({type:'start',id:startQuest,squad:squad.id})}>出発する<ArrowUpRight size={15}/></button></div>}

 </div>
 <div className={`cheer-gauge ${(run?.cheer||0)>=80?'charged':''}`}><div><Sparkles size={17}/><span>団長の応援</span><b>{run?.cheer||0} / 100</b></div><Progress value={run?.cheer||0} aria-label="団長の応援ゲージ"/><small>タップで +5。満タンになると全員で必殺技！</small></div>
 </div>
}
