'use client';
import {useState,type ReactNode} from 'react';
import {Coins,Leaf,Gem,Logs,Compass,Users,Flame,BookOpen,ChevronRight,Heart,Hammer,Gift,House,Lightbulb} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {PartyPanel} from './party-panel';
import {QuestPicker} from './quest-picker';
import {QuestCompletion} from './quest-completion';
import {Toaster} from '@/components/ui/sonner';
import {SavePanel} from './save-panel';
import {useGameMusic} from './use-game-music';
import {useJourneyHints} from './use-journey-hints';
import {MapStage} from './map-stage';
import {GuildHome} from './guild-home';
import {RecruitmentBoard,RareInventory} from './recruitment-board';
import {Banter,StoryLibrary,ConversationReader,StoryReader} from './story-scenes';
import {availableStories,characterNotes,journeyBanter,stories,storyProgress,together,type Story,type StoryLine} from '@/lib/stories';
import {Sprite} from './sprite';
import {InstallGuide,useInstallPrompt} from './install-guide';
import {nextGoal,partyPreview,questAdvice,type JourneyGoal} from '@/lib/journey';
import type {Action,State} from '@/lib/game';
import type {useLocalGame} from './use-local-game';
import {inPrologue,TRADE_QUEST,isPrologueQuest,stageEndingPending,restingQuest} from '@/lib/prologue';
import {heroes,availableQuests,allQuests,heroSkills,memberStats,activeBonds,bondLevel} from '@/lib/game';
type Game=ReturnType<typeof useLocalGame>;
type Sheet='book'|'quests'|'party'|'bag'|'journal'|'build'|'upgrade'|'gift'|'recruit'|'help'|'goal'|'preview'|'advice'|'install'|'stories'|'story'|'banter'|'personality'|null;
const fmt=(n:number)=>Math.floor(n).toLocaleString('ja-JP');
const compact=(n:number)=>n<10000?fmt(n):(n/10000).toFixed(n<100000?1:0)+'万';
export function PhoneGame({game}:{game:Game}){
 const installStatus=useInstallPrompt();
 const {s,clock,dispatch}=game;
 const prologue=inPrologue(s),pendingEnding=stageEndingPending(s),ending=pendingEnding?stories.find(st=>st.id===pendingEnding+'-return')!:null;
 const [pendingDeparture,setPendingDeparture]=useState<Action|null>(null);
 const [reading,setReading]=useState<Story|null>(null),[banterSnapshot,setBanterSnapshot]=useState<StoryLine[]>([]);
 const [view,setView]=useState('adventure'),[sheet,setSheet]=useState<Sheet>(null),[selectedSquad,setSquad]=useState('party-1'),[questChoices,setQuestChoices]=useState<Record<string,string>>({}),[heroIndex,setHeroIndex]=useState(0),[draft,setDraft]=useState<string[]>(s.squads[0].members);
 const sq=s.squads.find(p=>p.id===selectedSquad)||s.squads[0],run=sq.run,ready=game.ready&&!game.otherTab;
 const questId=run?.quest||(prologue?restingQuest(s,sq):questChoices[sq.id]||'herbs');
 function setQuest(id:string){setQuestChoices(current=>({...current,[sq.id]:id}));}
 const music=useGameMusic(view==='camp'||!run?'camp':'journey',ready);
 const unlocked=availableQuests(s),q=unlocked.find(q=>q.id===questId)||unlocked[0];
 const roster=heroes.filter(h=>s.owned.includes(h.id)),hi=Math.min(heroIndex,roster.length-1),hero=roster[hi];
 const synergy=activeBonds(sq.members);
 const [candidateQuest,setCandidateQuest]=useState(prologue?TRADE_QUEST:'herbs');
 const [returnIntent,setReturnIntent]=useState<{squad:string;destination:'adventure'|'companions';quest?:string}|null>(null);
 const [leaveAction,setLeaveAction]=useState<((state:State)=>void)|null>(null);
 const dirty=draft.join(',')!==sq.members.join(',');
 const activeQuest=allQuests.find(q=>q.id===run?.quest);
 const lines=synergy.length?synergy.flatMap(b=>b.lines):sq.members.map(id=>`${heroes.find(h=>h.id===id)!.name}「さあ、次の冒険へ！」`),quote=lines[Math.floor(clock/8000)%lines.length];
 const goal=nextGoal(s,sq),preview=partyPreview(s,sq,draft,q);
 const hints=useJourneyHints(game.profile?.id,goal);
 const banter=journeyBanter(s,sq,clock),memories=availableStories(s),unread=memories.filter(st=>!storyProgress(s).read.includes(st.id)).length;
 function openStory(st:Story){setReading(st);setSheet('story');}
 function act(action:Action,onSuccess?:(state:State)=>void){if(action.type==='start')action={...action,value:!isPrologueQuest(action.id||'')};const target=s.squads.find(p=>p.id===action.squad)||s.squads[0];const first=action.type==='start'&&!target.run&&together(target.members)&&!storyProgress(s).departed.includes(action.id||'');if(first){const st=stories.find(st=>st.id===action.id+'-departure');if(st){setPendingDeparture(action);openStory(st);return true;}}const ok=dispatch(action,onSuccess);if(ok&&action.type==='build'){setSheet(null);setView('camp');}if(ok&&action.type==='prepareRecruitment'){const st=stories.find(st=>st.id==='recruit-'+action.id+'-prepared');if(st)openStory(st);}if(ok&&action.type==='start'&&action.id?.startsWith('join-')){setSquad(action.squad||sq.id);setView('adventure');setSheet(null);}return ok;}
 function openQuests(id=q.id){leaveEditor(()=>{setCandidateQuest(id);setView('adventure');setSheet('quests');});}
 function followGoal(g:JourneyGoal){if(g.destination==='quests'){game.setReport(null);openQuests(g.questId||q.id);return;}leaveEditor(current=>{game.setReport(null);setSheet(null);if(g.questId)setQuest(g.questId);if(g.destination==='build'){setView('camp');setSheet('build');}else if(g.destination==='recruit'){setSheet('recruit');}else if(g.destination==='party'||g.destination==='companions'){setDraft(current.squads.find(p=>p.id===sq.id)!.members);setView('companions');}else setView(g.destination);});}
 function leaveEditor(next:(state:State)=>void){if(view==='companions'&&dirty)setLeaveAction(()=>next);else next(s);}
 function navigate(value:string){if(value===view){setSheet(null);return;}leaveEditor(current=>{if(value==='companions')setDraft(current.squads.find(p=>p.id===sq.id)!.members);setSheet(null);setView(value);});}
 function chooseSquad(id:string){if(id===sq.id){setSheet(null);return;}leaveEditor(current=>{const p=current.squads.find(p=>p.id===id)!;setSquad(id);setDraft(p.members);setSheet(null);});}
 function createSquad(){leaveEditor(()=>{act({type:'newSquad'},current=>{const created=current.squads[current.squads.length-1];setSquad(created.id);setDraft(created.members);setView('companions');setSheet(null);});});}
 function requestReturn(destination:'adventure'|'companions',quest?:string){setReturnIntent({squad:sq.id,destination,quest});}
 function confirmReturn(){if(!returnIntent)return;const target=s.squads.find(p=>p.id===returnIntent.squad);if(!target)return;if(act({type:'stop',squad:target.id})){setSquad(target.id);setDraft(target.members);if(returnIntent.quest)setQuest(returnIntent.quest);setView(returnIntent.destination);setSheet(null);setReturnIntent(null);}}
 function selectQuest(){const id=unlocked.find(item=>item.id===candidateQuest)?.id||q.id;if(run&&run.quest!==id){requestReturn('adventure',id);return;}setQuest(id);setSheet(null);setView('adventure');if(!run)act({type:'start',id,squad:sq.id});}
 function finishStory(){if(!reading)return false;const ok=pendingDeparture?dispatch({...pendingDeparture,readDeparture:true}):dispatch({type:'readStory',id:reading.id});if(ok)setPendingDeparture(null);return ok;}
 function closeStory(){setPendingDeparture(null);setSheet(reading?.chapter==='recruitment'?'recruit':null);}
 let title='',description='',content:ReactNode=null;
 if(sheet==='book'){title='旅の手帳';description='旅の記録と、手助けのヒント。';content=<div className="handbook-menu">{(!prologue||!!s.done[TRADE_QUEST])&&<button className="outline" onClick={()=> { setSheet('stories'); }}><BookOpen size={20}/><span>思い出{unread>0&&` · 未読 ${unread}`}</span><ChevronRight size={16}/></button>}<button className="outline" onClick={()=>{hints.markRead();setSheet('goal');}}><Lightbulb size={20}/><span>ヒント</span><ChevronRight size={16}/></button><SavePanel game={game} music={music}/></div>;}
 if(sheet==='stories'){title='旅の思い出';description='出会いも、冒険も、帰ってきた日のことも。';content=<><button className="outline" onClick={()=> { setSheet('journal'); }}>旅の記録</button><StoryLibrary state={s} onOpen={openStory}/></>;}
 if(sheet==='story'&&reading){title=reading.title;description=reading.place;content=<StoryReader key={reading.id} story={reading} ready={ready} onRead={finishStory} departure={!!pendingDeparture} onClose={closeStory}/>;}
 if(sheet==='banter'){title=activeQuest?.companion?'仲間になるまでの道中':'ふたりの道中';description=activeQuest?.name||'次の冒険を待ちながら';content=<ConversationReader lines={banterSnapshot} onClose={()=> { setSheet(null); }}/>;}
 if(sheet==='personality'){title=hero.name+'のこと';description=hero.job;const notes=characterNotes[hero.id];content=<><Sprite index={hero.sprite} size={88}/><p>{hero.bio}</p>{notes&&<p>{notes.habit}</p>}<div className="phone-stat-row">{['採取','護衛','討伐'].map((name,i)=><span key={name}>{name}<b>{memberStats(s,hero.id)[i]}</b></span>)}</div><h3>{heroSkills[hero.id].name}</h3><p>{heroSkills[hero.id].description}</p><button className="outline" onClick={()=> { navigate('memories'); }}>旅の思い出を読む</button></>; }
 if(sheet==='goal'){title=goal.title;description=prologue?'ふたりの次の一歩':'旅団の次の一歩';content=<><p>{goal.detail}</p>{(!prologue||goal.destination!=='quests')&&<button className="full" onClick={()=> { followGoal(goal); }}>{goal.action}</button>}{s.clears===0&&!prologue&&<ol className="journey-steps"><li>ふたりの隊を出発させる</li><li>タップで応援。見守るだけでも大丈夫</li><li>3地点ごとに報酬、15地点で依頼達成</li><li>木材とお金で、帰る場所を作る</li></ol>}<button className="outline full" onClick={()=> { setSheet('help'); }}>旅の手引き・操作方法</button></>;}
 if(sheet==='install'){title='ホーム画面に追加';description='ランタンから、いつもの冒険へ。';content=<InstallGuide onDownload={game.download} status={installStatus}/>;}
 if(sheet==='advice'){title='この依頼の支度';description=q.name;content=<><p>{questAdvice(s,sq,q)}</p><p>休憩が多いときは回復役や障壁を持つ仲間も頼りになります。編成の変更は帰還後に行えます。</p><button onClick={()=>{navigate('companions');setSheet(null);}}>仲間の編成へ</button>{run&&<button className="outline" onClick={()=> { setSheet('party'); }}>隊を選ぶ</button>}</>;}
 if(sheet==='preview'){title='編成の効果を比べる';description='現在の編成 → 選んでいる編成';content=<><div className="party-comparison">{['採取','護衛','討伐'].map((name,i)=><div key={name}><span>{name}</span><b>{preview.before[i]} → {preview.after[i]}</b><small>{preview.after[i]-preview.before[i]>0?'+':''}{preview.after[i]-preview.before[i]}</small></div>)}</div>{draft.length?<><p>「{q.name}」の所要時間の目安<br/>{Math.max(1,Math.round(preview.secondsBefore/60))}分 → {Math.max(1,Math.round(preview.secondsAfter/60))}分</p><small>手助け・休憩・特技によって実際の時間は変わります。</small><p>{preview.healing?'回復役が仲間を支えます。':'回復は団長の手助けでも支えられます。'}{preview.guarding&&'障壁で仲間を守れます。'}{preview.exploring&&'寄り道が得意な仲間がいます。'}</p>{preview.bonds.length?preview.bonds.map(b=><p className="phone-bond" key={b.name}><Heart size={14}/>{b.name} · 連携 Lv.{bondLevel(s,b.ids)}</p>):<p>この編成にはペアの連携がありません。仲間の得意分野で力を合わせます。</p>}<p>{questAdvice(s,{...sq,members:draft},q)}</p></>:<p>仲間を1人以上選んでください。</p>}<button disabled={!ready||!!run||!draft.length} onClick={()=>{act({type:'party',squad:sq.id,members:draft});setSheet(null);}}>この編成を保存</button>{run&&<p>冒険中の隊は帰還してから編成できます。</p>}</>;}

 if(sheet==='party'){title='冒険を見守る隊';description='隊を選ぶと、その隊の冒険と行き先を表示します。';content=<><div className="phone-squads">{s.squads.map(p=><button aria-pressed={p.id===sq.id} className={p.id===sq.id?'selected':''} onClick={()=> { chooseSquad(p.id); }} key={p.id}><span>{p.name}<small>{p.run?allQuests.find(q=>q.id===p.run?.quest)?.name:'拠点で待機中'}</small></span><span>{p.members.map(id=><Sprite key={id} index={heroes.find(h=>h.id===id)!.sprite} size={38}/>)}</span></button>)}</div><button className="outline" onClick={()=> { navigate('companions'); }}>隊を作る・編成する</button></>;}
 if(sheet==='quests'){title='クエスト';description=prologue?'行き先を選びましょう。':'出かけたいクエストを選びましょう。';content=<QuestPicker state={s} squad={sq} selected={candidateQuest} onSelect={setCandidateQuest} onConfirm={selectQuest} ready={ready}/>;}
 if(sheet==='bag'){title='持ちもの';description='区間報酬と寄り道で集めた、旅の蓄えです。';content=<><div className="inventory-grid">{[[Coins,s.gold,'お金'],[Leaf,s.herbs,'薬草'],[Gem,s.ore,'鉱石'],[Logs,s.wood,'木材']].map(([Icon,value,label])=>{const I=Icon as typeof Coins;return <div key={String(label)}><I/><span>{String(label)}</span><b>{fmt(value as number)}</b></div>})}</div><RareInventory state={s}/></>;}
 if(sheet==='journal'){title='旅団の足あと';description=`${s.clears}件達成 · 寄り道で${s.discoveries}回の発見`;content=<><button className="memory-link" onClick={()=> { setSheet('stories'); }}><Heart size={18}/>旅の思い出{unread>0&&<span>未読 {unread}</span>}</button><div className="phone-journal">{s.log.map((entry,i)=><article key={entry.at+'-'+i}><time>{new Date(entry.at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time><p>{entry.text}</p></article>)}</div></>;}
 if(sheet==='build'){title='拠点を育てる';description='木材を使って、仲間たちの帰る場所を作ります。';content=<div className="building-details"><GuildHome state={s} now={clock} ready={ready} onAction={act} onStory={openStory}/></div>;}
 if(sheet==='upgrade'){title='冒険の支度';description='全員に効果があります。';content=s.clears<3?<p>3件の依頼を達成すると、装備を強化できます。</p>:<div className="phone-upgrades"><article><Hammer/><h3>みんなの装備 Lv.{s.gear}</h3><p>1段階ごとに全能力 +8%</p><button disabled={!ready||s.gear>=15||s.gold<100*(s.gear+1)||s.ore<5*(s.gear+1)} onClick={()=>act({type:'gear'})}>{s.gear>=15?'最大レベル':`${100*(s.gear+1)} G · 鉱石 ${5*(s.gear+1)} で強化`}</button></article>{s.clears>=10&&<article><Flame/><h3>野営地 Lv.{s.camp}</h3><p>1段階ごとに行動間隔 −3.5%</p><button disabled={!ready||s.camp>=10||s.gold<150*(s.camp+1)||s.herbs<12*(s.camp+1)} onClick={()=>act({type:'camp'})}>{s.camp>=10?'最大レベル':`${150*(s.camp+1)} G · 薬草 ${12*(s.camp+1)} で改築`}</button></article>}</div>;}
 if(sheet==='gift'){title='ギルドの差し入れ';description='毎朝9時に届く、旅の応援です。';const claimed=s.lastDaily===new Date(clock||0).toISOString().slice(0,10);content=<><Gift className="gift-art"/><p>80 G と薬草 5 個</p><button disabled={!ready||claimed||s.clears<3} onClick={()=>act({type:'daily'})}>{claimed?'受取済み':s.clears<3?'3件達成で解放':'受け取る'}</button></>;}
 if(sheet==='recruit'){title='仲間になるまで';description='旅を重ねてつながる、新しい出会い。';content=<RecruitmentBoard state={s} squad={sq} ready={ready} onAction={act} onStory={openStory} onGather={id=> { openQuests(id); }} onWatch={id=>{setSquad(id);setView('adventure');setSheet(null);}}/>;}
 if(sheet==='help'){title='旅の手引き';description='見守るだけでも、手助けしても。';content=<><p>マップの空いているところや敵・素材をタップすると手助け、仲間やHP表示をタップするとパーティを回復できます。HPは隊全体で共有し、先頭の仲間の足元に表示します。休憩中はマップのどこでも回復できます。{!prologue&&'応援が100になると、全員の必殺技が発動！ '}タップでの手助けに回数制限はありません。</p>{!prologue&&<p>光る寄り道をタップすると、仲間が優先して調べます。放置でも自動で回収します。</p>}<p>1周は15地点。3地点ごとに報酬を確保します。行き先は巻物の「クエスト」から選べます。{!prologue&&'帰還は隊の名前の横、編成は「パーティ」から操作できます。'}</p><p>進行は端末に保存し、開いている間は約5分ごとにクラウドへバックアップします。画面を閉じた後は、次に開いたときに最大12時間分を集計します。</p><button className="outline full" onClick={()=> { setSheet('install'); }}>ホーム画面に追加</button></>;}
 return <main className={'phone-game'+(prologue?' prologue-game':'')}><Toaster theme="dark" position="top-center"/><header className="phone-header"><button className="phone-wallet" onClick={()=> { setSheet('bag'); }} aria-label="持ちものを開く"><span><Coins/>{compact(s.gold)}</span><span><Leaf/>{compact(s.herbs)}</span><span><Gem/>{compact(s.ore)}</span><span><Logs/>{compact(s.wood)}</span></button><button className="handbook-button" onClick={()=> { setSheet('book'); }} aria-label="旅の手帳：思い出・ヒント・設定"><BookOpen size={23}/>{(game.error||hints.unread||(!prologue&&unread>0))&&<i className="unread-dot" aria-hidden="true"/>}</button></header>
 {(game.error||game.otherTab)&&<div className="phone-notice" role="status"><span>{game.otherTab?'別のタブで冒険中です':game.error}</span>{game.otherTab&&<button onClick={game.takeOver}>ここで続ける</button>}</div>}


 <Tabs className="phone-tabs" value={view} onValueChange={navigate}>
 <div className="phone-screen">
 <TabsContent value="adventure" className="phone-adventure">{!prologue&&<div className="adventure-toolbar"><button className="squad-selector" onClick={()=> { setSheet('party'); }} aria-label={'冒険する隊を選ぶ：'+sq.name}><Users size={16}/><span>{sq.name}</span><ChevronRight size={14}/></button>{run&&<button className="outline return-button" disabled={!ready} onClick={()=> { requestReturn('adventure'); }}><House size={15}/>帰還</button>}<button className="outline edit-party" onClick={()=> { navigate('companions'); }}>編成</button></div>}<div className="adventure-destination"><div>{(!prologue||run)&&<b>{activeQuest?.name||q.name}</b>}</div><div className="quest-control"><button className={'outline quest-entry'+(prologue&&!run&&!s.done[TRADE_QUEST]?' quest-entry-guided':'')} aria-label="クエストを開く" aria-describedby={prologue&&!run&&!s.done[TRADE_QUEST]?'quest-tutorial':undefined} onClick={()=> { openQuests(); }}><img src="/ui/quest-scroll.png" width={52} height={52} alt=""/></button>{prologue&&!run&&!s.done[TRADE_QUEST]&&<div className="quest-tutorial" id="quest-tutorial" role="status">ここから<br/><b>クエストを選ぼう</b></div>}</div></div><MapStage state={s} squad={sq} now={clock} ready={ready} onAction={act} startQuest={q.id} paused={!!sheet||!!returnIntent||!!leaveAction||!!game.report||!!ending}/>{banter.length?<Banter key={(game.profile?.id||'')+':'+sq.id+':'+(run?.quest||'idle')} lines={banter} paused={!!sheet||!!ending||!!game.report||!ready} onRead={lines=>{setBanterSnapshot(lines);setSheet('banter');}}/>:<div className="phone-banter"><p>{quote}</p></div>}</TabsContent>

 <TabsContent value="companions" className="phone-party"><PartyPanel state={s} squad={sq} draft={draft} ready={ready} onChoose={chooseSquad} onCreate={createSquad} onToggle={id=> { setDraft(d=>d.includes(id)?d.filter(member=>member!==id):[...d,id]); }} onInspect={id=>{setHeroIndex(roster.findIndex(h=>h.id===id));setSheet('personality');}} onSave={()=>act({type:'party',squad:sq.id,members:draft})} onDiscard={()=> { setDraft(sq.members); }} onReturn={()=> { requestReturn('companions'); }} onRecruit={()=> { leaveEditor(()=> { setSheet('recruit'); }); }} onPreview={()=> { setSheet('preview'); }} onAdventure={()=> { navigate('adventure'); }}/></TabsContent>
 <TabsContent value="camp" className="phone-home"><div className="screen-heading"><h2>帰る場所</h2><span className="home-level">{['野営地','酒場','小さな村'][s.town]}</span></div><GuildHome state={s} now={clock} ready={ready} onAction={act} onStory={openStory}/><div className="home-menu"><button onClick={()=> { setSheet('build'); }}><House/><span>建設</span></button><button onClick={()=> { setSheet('upgrade'); }}><Hammer/><span>強化</span></button><button onClick={()=> { setSheet('gift'); }}><Gift/><span>差し入れ</span></button></div></TabsContent>
 <TabsContent value="memories" className="phone-memories"><div className="screen-heading"><h2>旅の思い出</h2><button className="outline" onClick={()=> { setSheet('journal'); }}>旅の記録</button></div><StoryLibrary state={s} onOpen={openStory}/></TabsContent>
 </div><TabsList className="phone-navigation"><TabsTrigger value="adventure"><Compass/><span>冒険</span></TabsTrigger>{!prologue&&<><TabsTrigger value="companions"><Users/><span>パーティ</span></TabsTrigger><TabsTrigger value="camp"><Flame/><span>拠点</span></TabsTrigger></>}</TabsList></Tabs>
 <Dialog open={!!sheet&&!ending} onOpenChange={open=>{if(!open&&sheet!=='story')setSheet(null);}}><DialogContent showCloseButton={sheet!=='story'} onInteractOutside={event=>{if(sheet==='story')event.preventDefault();}} onEscapeKeyDown={event=>{if(sheet==='story')event.preventDefault();}} className={"phone-dialog"+(sheet==='story'?' story-dialog':'')+(sheet==='quests'?' quest-dialog':'')}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{content}</DialogContent></Dialog>
 {ending&&<QuestCompletion key={game.profile?.id+':'+ending.id} story={ending} questName={allQuests.find(q=>q.id===ending.quest)!.name} ready={ready} onRead={()=>dispatch({type:'readStory',id:ending.id})} onClose={()=>{game.setReport(null);setSheet(null);}}/>}
 <AlertDialog open={!!returnIntent} onOpenChange={open=>{if(!open)setReturnIntent(null)}}><AlertDialogContent className="game-confirm"><AlertDialogHeader><AlertDialogTitle>{returnIntent?.destination==='companions'?'帰還して編成しますか？':returnIntent?.quest?'帰還して行き先を変えますか？':'帰還しますか？'}</AlertDialogTitle><AlertDialogDescription>{s.squads.find(p=>p.id===returnIntent?.squad)?.name}の確保済みの区間報酬は残ります。途中の依頼は最初からになります。{returnIntent?.quest&&'帰還後に行き先を選び直します。自動では出発しません。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>冒険を続ける</AlertDialogCancel><AlertDialogAction disabled={!ready} onClick={e=>{e.preventDefault();confirmReturn();}}>{returnIntent?.destination==='companions'?'帰還して編成する':'帰還する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!leaveAction} onOpenChange={open=>{if(!open)setLeaveAction(null)}}><AlertDialogContent className="game-confirm"><AlertDialogHeader><AlertDialogTitle>編成の変更を保存しますか？</AlertDialogTitle><AlertDialogDescription>選んだ仲間の変更がまだ保存されていません。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>編成に戻る</AlertDialogCancel><button className="outline" onClick={()=>{const next=leaveAction;setDraft(sq.members);setLeaveAction(null);next?.(s);}}>変更を破棄して続ける</button><AlertDialogAction disabled={!ready||!draft.length||!!run} onClick={e=>{e.preventDefault();act({type:'party',squad:sq.id,members:draft},current=>{const next=leaveAction;setLeaveAction(null);next?.(current);});}}>保存して続ける</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!game.report&&!sheet&&!ending} onOpenChange={open=>{if(!open)game.setReport(null)}}><DialogContent className="phone-dialog"><DialogHeader><DialogTitle>{prologue?'留守の間の交易':'おかえりなさい、団長。'}</DialogTitle><DialogDescription>留守の間の冒険で集めたものです。</DialogDescription></DialogHeader>{game.report&&<><p>{game.report.count}件の依頼を達成</p><div className="offline-loot"><span>{fmt(game.report.gold)} G</span><span>薬草 {game.report.herbs}</span><span>鉱石 {game.report.ore}</span><span>木材 {game.report.wood}</span></div><span>仲間の経験値 +{game.report.xp}</span>{game.report.capped&&<small>最大12時間分を集計しました。</small>}{!prologue&&<div className="return-goal"><small>次の楽しみ</small><h3>{goal.title}</h3><p>{goal.detail}</p><button className="full" onClick={()=> { followGoal(goal); }}>{goal.action}</button></div>}<button className="outline full" onClick={()=> { game.setReport(null); }}>冒険を見守る</button></>}</DialogContent></Dialog>
 </main>;
}
