'use client';
import {useState,type ReactNode} from 'react';
import {Sparkles,Coins,Leaf,Gem,Logs,Compass,Users,Flame,BookOpen,ScrollText,ChevronLeft,ChevronRight,Heart,Shield,Swords,Hammer,Gift,House,UserPlus,Plus,Pause,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {SavePanel} from './save-panel';
import {MapStage} from './map-stage';
import {GuildHome} from './guild-home';
import {Sprite} from './sprite';
import type {useLocalGame} from './use-local-game';
import {heroes,quests,heroSkills,stats,memberStats,power,level,activeBonds,bondLevel,memberLimit,squadLimit,estimate} from '@/lib/game';
type Game=ReturnType<typeof useLocalGame>;
type Sheet='party'|'bag'|'journal'|'build'|'upgrade'|'gift'|'recruit'|'help'|null;
const fmt=(n:number)=>Math.floor(n).toLocaleString('ja-JP');
const compact=(n:number)=>n<10000?fmt(n):(n/10000).toFixed(n<100000?1:0)+'万';
export function PhoneGame({game}:{game:Game}){
 const {s,clock,dispatch:act}=game;
 const [view,setView]=useState('adventure'),[sheet,setSheet]=useState<Sheet>(null),[selectedSquad,setSquad]=useState('party-1'),[questId,setQuest]=useState('herbs'),[heroIndex,setHeroIndex]=useState(0),[draft,setDraft]=useState<string[]>(s.squads[0].members);
 const sq=s.squads.find(p=>p.id===selectedSquad)||s.squads[0],run=sq.run,ready=game.ready&&!game.otherTab;
 const unlocked=quests.filter(q=>q.unlock<=s.clears),q=unlocked.find(q=>q.id===questId)||unlocked[0],questIndex=unlocked.indexOf(q);
 const roster=heroes.filter(h=>s.owned.includes(h.id)),hi=Math.min(heroIndex,roster.length-1),hero=roster[hi],other=s.squads.find(p=>p.id!==sq.id&&p.members.includes(hero.id));
 const synergy=activeBonds(sq.members),ps=stats(s,sq),nextRecruit=heroes.find(h=>!s.owned.includes(h.id)&&h.unlock<=s.clears),nextQuest=quests.find(q=>q.unlock>s.clears);
 const activeQuest=quests.find(q=>q.id===run?.quest);
 const lines=synergy.length?synergy.flatMap(b=>b.lines):sq.members.map(id=>`${heroes.find(h=>h.id===id)!.name}「さあ、次の冒険へ！」`),quote=lines[Math.floor(clock/8000)%lines.length];
 function navigate(value:string){if(value==='companions')setDraft(sq.members);setView(value);}
 function chooseSquad(id:string){const p=s.squads.find(p=>p.id===id)!;setSquad(id);setDraft(p.members);setSheet(null);}
 function departure(){act({type:'start',id:q.id,squad:sq.id});setView('adventure');}
 let title='',description='',content:ReactNode=null;
 if(sheet==='party'){title='パーティ';description='隊を切り替えたり、周回と編成を設定できます。';content=<><div className="phone-squads">{s.squads.map(p=><button className={p.id===sq.id?'selected':''} onClick={()=>chooseSquad(p.id)} key={p.id}><span>{p.name}<small>{p.run?quests.find(q=>q.id===p.run?.quest)?.name:'待機中'}</small></span><span>{p.members.map(id=><Sprite key={id} index={heroes.find(h=>h.id===id)!.sprite} size={38}/>)}</span></button>)}</div><div className="phone-stat-row">{['採取','護衛','討伐'].map((name,i)=><span key={name}>{name}<b>{ps[i]}</b></span>)}</div>{synergy.map(b=><p className="phone-bond" key={b.name}><Heart size={14}/>{b.name} · 連携 Lv.{bondLevel(s,b.ids)}</p>)}<button className="outline" onClick={()=>{navigate('companions');setSheet(null)}}>編成を開く</button><label className="switch-row"><span>クリア後に自動周回</span><Switch checked={sq.repeat} disabled={!ready} onCheckedChange={value=>act({type:'repeat',squad:sq.id,value})} aria-label="自動周回"/></label>{run&&<AlertDialog><AlertDialogTrigger asChild><button className="outline"><Pause size={15}/>この隊を帰還させる</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>帰還しますか？</AlertDialogTitle><AlertDialogDescription>確保済みの区間報酬は残ります。途中の依頼は最初からになります。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>冒険を続ける</AlertDialogCancel><AlertDialogAction onClick={()=>{act({type:'stop',squad:sq.id});setSheet(null)}}>帰還する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}{squadLimit(s)>s.squads.length&&<button disabled={!ready||!s.owned.some(id=>s.squads.every(p=>!p.members.includes(id)))} onClick={()=>act({type:'newSquad'})}><Plus size={15}/>新しい隊を作る</button>}<small>仲間4人で2隊、6人で3隊を編成できます。</small></>;}
 if(sheet==='bag'){title='持ちもの';description='区間報酬と寄り道で集めた、旅の蓄えです。';content=<div className="inventory-grid">{[[Coins,s.gold,'お金'],[Leaf,s.herbs,'薬草'],[Gem,s.ore,'鉱石'],[Logs,s.wood,'木材']].map(([Icon,value,label])=>{const I=Icon as typeof Coins;return <div key={String(label)}><I/><span>{String(label)}</span><b>{fmt(value as number)}</b></div>})}</div>;}
 if(sheet==='journal'){title='旅団の足あと';description=`${s.clears}件達成 · 寄り道で${s.discoveries}回の発見`;content=<div className="phone-journal">{s.log.map((entry,i)=><article key={entry.at+'-'+i}><time>{new Date(entry.at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time><p>{entry.text}</p></article>)}</div>;}
 if(sheet==='build'){title='拠点を育てる';description='木材を使って、仲間たちの帰る場所を作ります。';content=<div className="building-details"><GuildHome state={s} now={clock} ready={ready} onAction={act}/></div>;}
 if(sheet==='upgrade'){title='冒険の支度';description='全員に効果があります。';content=s.clears<3?<p>3件の依頼を達成すると、装備を強化できます。</p>:<div className="phone-upgrades"><article><Hammer/><h3>みんなの装備 Lv.{s.gear}</h3><p>1段階ごとに全能力 +8%</p><button disabled={!ready||s.gear>=15||s.gold<100*(s.gear+1)||s.ore<5*(s.gear+1)} onClick={()=>act({type:'gear'})}>{s.gear>=15?'最大レベル':`${100*(s.gear+1)} G · 鉱石 ${5*(s.gear+1)} で強化`}</button></article>{s.clears>=10&&<article><Flame/><h3>野営地 Lv.{s.camp}</h3><p>1段階ごとに行動間隔 −3.5%</p><button disabled={!ready||s.camp>=10||s.gold<150*(s.camp+1)||s.herbs<12*(s.camp+1)} onClick={()=>act({type:'camp'})}>{s.camp>=10?'最大レベル':`${150*(s.camp+1)} G · 薬草 ${12*(s.camp+1)} で改築`}</button></article>}</div>;}
 if(sheet==='gift'){title='ギルドの差し入れ';description='毎朝9時に届く、旅の応援です。';const claimed=s.lastDaily===new Date(clock||0).toISOString().slice(0,10);content=<><Gift className="gift-art"/><p>80 G と薬草 5 個</p><button disabled={!ready||claimed||s.clears<3} onClick={()=>act({type:'daily'})}>{claimed?'受取済み':s.clears<3?'3件達成で解放':'受け取る'}</button></>;}
 if(sheet==='recruit'){title='新しい出会い';description=nextRecruit?'旅をともにする仲間を迎えよう。':'冒険を重ねると、新しい仲間に出会えます。';content=nextRecruit?<><div className="recruit-portrait"><Sprite index={nextRecruit.sprite} size={120}/><h3>{nextRecruit.name}</h3><p>{nextRecruit.job}</p></div><p>{nextRecruit.bio}</p><button disabled={!ready||s.gold<nextRecruit.price} onClick={()=>act({type:'recruit',id:nextRecruit.id})}>{nextRecruit.price} G で迎える</button></>:<p>今は、次の出会いを待っています。</p>;}
 if(sheet==='help'){title='旅の手引き';description='見守るだけでも、手助けしても。';content=<><p>敵や素材をタップすると加勢できます。応援が100になると、全員の必殺技が発動！ 回数制限はありません。</p><p>光る寄り道をタップすると、仲間が優先して調べます。放置でも自動で回収します。</p><p>1周は15地点。3地点ごとに報酬を確保します。隊の設定は、マップの上にあるパーティ名から開けます。</p><p>進行は端末に保存し、開いている間は約5分ごとにクラウドへバックアップします。</p></>;}
 return <main className="phone-game"><Toaster theme="dark" position="top-center"/><header className="phone-header"><div className="phone-brand"><Sparkles/><div><h1>星灯りの旅団</h1><span>{game.profile?.test?'テスト用の冒険':game.profile?.name||'旅の支度中…'}</span></div></div><button className="icon-button" aria-label="旅の記録" onClick={()=>setSheet('journal')}><BookOpen size={19}/></button><SavePanel game={game}/></header>
 <button className="phone-wallet" onClick={()=>setSheet('bag')} aria-label="持ちものを開く"><span><Coins/>{compact(s.gold)}</span><span><Leaf/>{compact(s.herbs)}</span><span><Gem/>{compact(s.ore)}</span><span><Logs/>{compact(s.wood)}</span></button>
 {(game.error||game.otherTab)&&<div className="phone-notice" role="status"><span>{game.otherTab?'別のタブで冒険中です':game.error}</span>{game.otherTab&&<button onClick={game.takeOver}>ここで続ける</button>}</div>}
 <Tabs className="phone-tabs" value={view} onValueChange={navigate}>
 <div className="phone-screen">
 <TabsContent value="adventure" className="phone-adventure"><div className="adventure-toolbar"><button onClick={()=>setSheet('party')}><Users size={16}/><span>{sq.name}</span><small>{sq.members.length}人</small></button><button className="icon-button" onClick={()=>setSheet('help')} aria-label="遊び方"><Info size={18}/></button></div><MapStage state={s} squad={sq} now={clock} ready={ready} onAction={act} startQuest={q.id}/><div className="phone-banter"><span>“</span><p>{quote}</p></div></TabsContent>
 <TabsContent value="quests" className="phone-quests"><div className="screen-heading"><h2>届いた依頼</h2><small>{questIndex+1} / {unlocked.length}</small></div><div className="quest-pager"><button className="icon-button" disabled={questIndex===0} aria-label="前の依頼" onClick={()=>setQuest(unlocked[questIndex-1].id)}><ChevronLeft/></button><span>{q.kind} · {Math.max(1,Math.round(estimate(s,sq,q)/60))}分ほど</span><button className="icon-button" disabled={questIndex===unlocked.length-1} aria-label="次の依頼" onClick={()=>setQuest(unlocked[questIndex+1].id)}><ChevronRight/></button></div><article className="phone-quest-detail"><span className="eyebrow">{q.region}</span><h3>{q.name}</h3><p>{q.desc}</p><div className="quest-rewards"><span><Coins size={17}/>{q.gold} G</span><span>EXP {q.xp}</span><span><Leaf size={15}/>{q.herbs}</span><span><Gem size={15}/>{q.ore}</span></div><div className="phone-aptitude"><span>{q.kind}の力 <b>{power(s,sq,q)}</b> / 目安 {q.need}</span><small>{power(s,sq,q)>=q.need?'得意な依頼':'手助けがあると安心'}</small></div><small>全15地点。3地点ごとに報酬を確保します。</small></article><div className="quest-depart"><button className="full" disabled={!ready||!!run} onClick={departure}>{run?'この隊は冒険中':'この依頼へ出発'}</button>{run?<button className="quiet full" onClick={()=>setView('adventure')}>{activeQuest?.name}を見守る</button>:<small>{nextQuest?`あと ${nextQuest.unlock-s.clears} 件で新しい依頼`:'すべての依頼を発見しました'}</small>}</div></TabsContent>
 <TabsContent value="companions" className="phone-companions"><div className="screen-heading"><h2>仲間</h2><button className="icon-button" onClick={()=>setSheet('recruit')} aria-label="新しい仲間を迎える"><UserPlus/>{nextRecruit&&<i/>}</button></div><div className="party-slots"><button className="icon-button" onClick={()=>setSheet('party')} aria-label="パーティを選ぶ"><Users/></button><span>{sq.name}</span><small>{draft.length}/{Math.max(memberLimit(s),sq.members.length)} 人</small><button disabled={!ready||!!run||!draft.length} onClick={()=>act({type:'party',squad:sq.id,members:draft})}>編成を保存</button></div><div className="quest-pager"><button className="icon-button" aria-label="前の仲間" disabled={hi===0} onClick={()=>setHeroIndex(hi-1)}><ChevronLeft/></button><span>{hi+1} / {roster.length}</span><button className="icon-button" aria-label="次の仲間" disabled={hi>=roster.length-1} onClick={()=>setHeroIndex(hi+1)}><ChevronRight/></button></div><article className="phone-hero-card"><div className="phone-hero-title"><Sprite index={hero.sprite} size={106}/><div><small>{hero.job}</small><h3>{hero.name}</h3><span>Lv.{level(s.xp[hero.id]||0)}</span></div></div><p>{hero.bio}</p><div className="phone-stat-row">{[[Leaf,'採取'],[Shield,'護衛'],[Swords,'討伐']].map(([Icon,name],i)=>{const I=Icon as typeof Leaf;return <span key={String(name)}><I size={15}/>{String(name)}<b>{memberStats(s,hero.id)[i]}</b></span>})}</div><div className="phone-skill"><b><Sparkles size={14}/>{heroSkills[hero.id].name}</b><p>{heroSkills[hero.id].description}</p></div></article><button className="full hero-pick" disabled={!ready||!!run||!!other||(!draft.includes(hero.id)&&draft.length>=Math.max(memberLimit(s),sq.members.length))} onClick={()=>setDraft(d=>d.includes(hero.id)?d.filter(id=>id!==hero.id):[...d,hero.id])}>{run?'帰還してから編成できます':other?`${other.name}に所属`:draft.includes(hero.id)?'編成から外す':'編成に加える'}</button></TabsContent>
 <TabsContent value="camp" className="phone-home"><div className="screen-heading"><h2>帰る場所</h2><span className="home-level">{['野営地','酒場','小さな村'][s.town]}</span></div><GuildHome state={s} now={clock} ready={ready} onAction={act}/><div className="home-menu"><button onClick={()=>setSheet('build')}><House/><span>建設</span></button><button onClick={()=>setSheet('upgrade')}><Hammer/><span>強化</span></button><button onClick={()=>setSheet('gift')}><Gift/><span>差し入れ</span></button></div></TabsContent>
 </div><TabsList className="phone-navigation"><TabsTrigger value="adventure"><Compass/><span>冒険</span></TabsTrigger><TabsTrigger value="quests"><ScrollText/><span>依頼</span></TabsTrigger><TabsTrigger value="companions"><Users/><span>仲間</span></TabsTrigger><TabsTrigger value="camp"><Flame/><span>拠点</span></TabsTrigger></TabsList></Tabs>
 <Dialog open={!!sheet} onOpenChange={open=>{if(!open)setSheet(null)}}><DialogContent className="phone-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{content}</DialogContent></Dialog>
 <Dialog open={!!game.report} onOpenChange={open=>{if(!open)game.setReport(null)}}><DialogContent className="phone-dialog"><DialogHeader><DialogTitle>おかえりなさい、団長。</DialogTitle><DialogDescription>留守の間の冒険で集めたものです。</DialogDescription></DialogHeader>{game.report&&<><p>{game.report.count}件の依頼を達成</p><div className="offline-loot"><span>{fmt(game.report.gold)} G</span><span>薬草 {game.report.herbs}</span><span>鉱石 {game.report.ore}</span><span>木材 {game.report.wood}</span></div>{game.report.capped&&<small>最大12時間分を集計しました。</small>}<button onClick={()=>game.setReport(null)}>冒険を続ける</button></>}</DialogContent></Dialog>
 </main>;
}
