import type { Story, StoryLine } from "./stories.ts";
import { GUILD_FOUNDING_QUEST } from "./chapter-four.ts";

const line = (
  speaker: string,
  text: string,
  expression: NonNullable<StoryLine["expression"]>,
): StoryLine => ({ speaker, text, expression });
const narration = (text: string): StoryLine => ({ text });

export const guildStories: Story[] = [
  {
    id: "guild-first-harvest",
    title: "収穫の一行",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      narration("レオンが収穫の記録を開く。リコは最初の一行の横へ、小さな印を書き込んだ。"),
      line("leon", "この印は、何ですか。", "neutral"),
      line("lico", "次に比べる分。全部使わないで。", "serious"),
      line("aria", "じゃあ、残す数も書いとこう。印だけだと、私、使っちゃうよ。", "worried"),
      line("lico", "……二つ。あたしが書く。", "neutral"),
      narration("リコは印の横に数を書き足した。レオンが、次の収穫用に一行空ける。"),
      line("lico", "その次も、空けといて。", "smile"),
    ],
  },
  {
    id: "guild-waiting-for-a-charm",
    title: "おまじないを待つ",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      narration("リコが瓶の底を二度軽く叩き、指先で蓋をなぞった。"),
      line("aria", "それ、何か変わるの？", "neutral"),
      line("lico", "変わらない。おまじない。", "neutral"),
      line("aria", "リコもそういうのするんだ。", "smile"),
      line("lico", "効かないよ。でも、やらないと落ち着かない。", "neutral"),
      line("aria", "じゃあ、待つね。", "smile"),
      narration("リコが顔を上げる。アリアは薬草を持ったまま、瓶から手を引いている。"),
      line("lico", "……先に、そっちを並べてもいいのに。", "shy"),
      line("aria", "うん。終わったら教えて。どこに置いたらいいか、聞きたいから。", "smile"),
      narration("リコは蓋から手を離し、机の自分に近い場所を空けた。"),
    ],
  },
  {
    id: "guild-readable-labels",
    title: "読める字と読めない札",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      line("leon", "この三本、同じ印に見えるんですが。", "worried"),
      line("lico", "違う。線が一つ多い。", "neutral"),
      line("leon", "その線を、瓶を開ける前に分かるようにしたいんです。", "serious"),
      line("lico", "あたしが開けるから。", "neutral"),
      line("leon", "掃除のとき、誰かが動かします。", "serious"),
      narration("リコが棚を見て、隣のお茶の缶を見る。"),
      line("lico", "……こっちへ寄せる。文字、書いてくれる？", "worried"),
      line("leon", "名前を教えてください。", "neutral"),
      line("lico", "右、触らない。左、もっと触らない。", "neutral"),
      line("leon", "名前をお願いします。", "serious"),
      narration("リコは椅子を寄せ、渋々手帳を開いた。レオンはお茶の缶を別の棚へ移す。"),
    ],
  },
  {
    id: "guild-which-finger",
    title: "どっちの指",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      line("mira", "リコ、指を見せて。赤くなっているわ。", "worried"),
      line("lico", "軟膏はだめ。試料に混ざる。", "serious"),
      line("mira", "試料は、もう蓋をしたでしょう。", "serious"),
      line("lico", "あとで開ける。", "neutral"),
      line("mira", "あとでは、手を洗ってからにしましょう。", "serious"),
      narration("リコは一度だけ戸棚を見て、手を出した。軟膏を塗るミラの指にも、小さな荒れがある。"),
      line("lico", "そっちは？", "worried"),
      line("mira", "私のは、あとで。", "smile"),
      line("lico", "いま瓶、開いてるのに。", "serious"),
      narration("ミラが手を止める。リコは軟膏の蓋を机へ伏せ、待っている。"),
      line("mira", "……そうね。私の指にも、お願いできる？", "shy"),
      line("lico", "うん。これなら、量は分かる。", "smile"),
    ],
  },
  {
    id: "guild-a-better-sales-pitch",
    title: "高く売れる説明",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      line("finn", "それ、また新しい薬かい？", "neutral"),
      line("lico", "ソーダ。終わったあとの分。今日は別の葉を入れた。", "smile"),
      line("finn", "その色で、泡まで出るのか。高く売れそうだねえ。", "mischievous"),
      line("lico", "売らないよ。", "neutral"),
      line("finn", "自分で飲むには、ずいぶん大きい瓶だ。", "smile"),
      line("lico", "次の分もある。", "neutral"),
      line("finn", "おじさんにも一口、どう？", "smile"),
      line("lico", "飲んでみて。理論上は大丈夫。", "smile"),
      narration("フィンは伸ばした手を、机の上で止める。"),
      line("finn", "売り文句は、俺に任せた方がいいな。", "worried"),
      line("lico", "あたしは飲んだ。苦いの好きなら、分ける。", "neutral"),
      line("finn", "……今日はお茶にしとこう。", "worried"),
      narration("リコはうなずき、空のカップを引っ込めた。断られた分をこっそり混ぜたりはしない。"),
    ],
  },
  {
    id: "guild-a-cup-at-the-desk",
    title: "留守番の一杯",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      line("finn", "返事はこれで全部。お茶、頼んでいいかい。", "smile"),
      line("mira", "ええ。お湯を沸かしたら、薬を届けに――", "smile"),
      line("finn", "向こうは夕方でいいって書いてあるよ。ここ。", "neutral"),
      line("mira", "そうね。でも、早くても困らないかもしれないわ。", "neutral"),
      line("finn", "俺が困る。どこまで蒸らすか、分からなくてね。", "mischievous"),
      narration("ミラは茶葉の缶を開け、フィンの置いた二つのカップを見る。"),
      line("mira", "急いでいても、ここは待ちましょう。", "serious"),
      line("finn", "おう。座って待とう。", "smile"),
      narration("ミラが椅子へ座る。フィンも腰を下ろし、返事の束を机の奥へ押した。"),
      line("mira", "あなたの配達は、もう済んだの？", "neutral"),
      line("finn", "……茶を飲んだら、すぐに。", "worried"),
      line("mira", "では、飲み終わったら一緒に出ましょう。配達先まで、ご一緒するわ。", "smile"),
      narration("フィンは笑ってカップを持ち上げたが、中はまだ空だった。"),
    ],
  },
  {
    id: "guild-a-reason-to-visit",
    title: "来る理由",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      narration("アリアが包みを机へ置く。レオンは窓を開けて、粉の入った袋を端へ寄せる。"),
      line("aria", "お茶。忘れなかったよ。", "smile"),
      line("leon", "茶器は出してある。菓子は、これから焼く。", "smile"),
      line("aria", "まだできてないんだ。", "surprised"),
      line("leon", "焦げる前から呼ぶ約束だっただろ。下の台所を借りてある。", "smile"),
      narration("アリアが包みをほどく手を止める。"),
      line("aria", "そうだった。じゃあ、ちゃんと手伝う。", "shy"),
      line("leon", "胡桃を割ってくれるか。", "neutral"),
      line("aria", "任せて。大きい欠片、残すね。", "smile"),
      narration("二人で階下へ降りる。受付机の箱には、新しい依頼は入っていない。"),
      line("aria", "今日、何も届いてなくてよかった。", "smile"),
      line("leon", "ああ。ゆっくり焼ける。", "smile"),
    ],
  },
  {
    id: "guild-the-second-shelf",
    title: "棚の二段目",
    place: "リンデ・倉庫の二階",
    quest: GUILD_FOUNDING_QUEST,
    chapter: "guild",
    lines: [
      narration(
        "戸口の札の裏に、「来たけど、いなかった。アリア」とある。その下へ、違う筆跡で「胡桃、棚の二段目。レオン」と書き足されていた。",
      ),
      line("aria", "見つけたよ。昨日。私の分？", "smile"),
      line("leon", "ああ。次に焼くときの分も、残してある。", "smile"),
      line("aria", "じゃあ、ここに印つけとく。受け取りました、って。", "smile"),
      narration("アリアが小さな胡桃を描く。フィンが戸口からのぞき込んだ。"),
      line("finn", "その印は何だい。新しい依頼？", "neutral"),
      line("aria", "おやつ。", "smile"),
      line("leon", "受け取りの確認です。", "shy"),
      narration("二人の声が重なる。フィンは札と二人を順に見た。"),
      line("finn", "……食べたってことね。", "thoughtful"),
      line("aria", "そう。次に来る日も、書いとこう。", "smile"),
      narration(
        "レオンが筆を渡す。アリアは二人で菓子を焼ける日を確かめてから、胡桃の印の隣へ日付を書いた。",
      ),
    ],
  },
];
