// Heroes, quests, pairs and levelling shared by the story mode.
// Extracted from the removed v1 module so the migration chain could go.
export type Kind = "採取" | "護衛" | "討伐";
export const heroes = [
  {
    id: "aria",
    name: "アリア",
    job: "風読みのレンジャー",
    mark: "弓",
    color: "#7ab4a1",
    stats: [22, 10, 14],
    price: 0,
    trait: "採取の達人",
    bio: "風の匂いで薬草を見つける。方向音痴は秘密。",
  },
  {
    id: "leon",
    name: "レオン",
    job: "暁の剣士",
    mark: "剣",
    color: "#d3a070",
    stats: [8, 17, 24],
    price: 0,
    trait: "魔物に強い",
    bio: "真面目な剣士。地図より仲間の言葉を信じる。",
  },
  {
    id: "mira",
    name: "ミラ",
    job: "月詠みの治癒師",
    mark: "月",
    color: "#ab9ac7",
    stats: [16, 22, 8],
    price: 0,
    trait: "護衛の心得",
    bio: "穏やかな旅団のお姉さん。お茶へのこだわりは強い。",
  },
  {
    id: "finn",
    name: "フィン",
    job: "いたずら好きの盗賊",
    mark: "影",
    color: "#bdb97d",
    stats: [24, 8, 17],
    price: 0,
    trait: "宝探し名人",
    bio: "宝箱には目がない。ミラには頭が上がらない。",
  },
  {
    id: "garr",
    name: "ガル",
    job: "山岳の守護騎士",
    mark: "盾",
    color: "#84a6b9",
    stats: [10, 36, 22],
    price: 450,
    trait: "鉄壁の守り",
    bio: "大きな盾と小さな裁縫道具を持つ、心優しい騎士。",
  },
  {
    id: "luna",
    name: "ルナ",
    job: "星屑の魔法使い",
    mark: "星",
    color: "#ada1df",
    stats: [20, 12, 38],
    price: 700,
    trait: "魔法の一撃",
    bio: "古代の星を研究中。夜ふかし仲間を探している。",
  },
  {
    id: "poppy",
    name: "ポピー",
    job: "森の錬金術師",
    mark: "葉",
    color: "#8ec293",
    stats: [40, 19, 12],
    price: 950,
    trait: "豊かな収穫",
    bio: "失敗した薬も「新しい味」と言い張る研究家。",
  },
  {
    id: "noel",
    name: "ノエル",
    job: "旅する吟遊詩人",
    mark: "詩",
    color: "#d69daa",
    stats: [22, 34, 23],
    price: 1300,
    trait: "旅路の歌",
    bio: "まだ見ぬ旅団の伝説を、一番近くで歌いたい。",
  },
];
export const quests = [
  {
    id: "herbs",
    name: "月しずく草の採取",
    kind: "採取" as Kind,
    region: "ささやきの森",
    desc: "月明かりを蓄える薬草を、薬師のもとへ。",
    tier: 1,
    need: 30,
    seconds: 60,
    gold: 32,
    xp: 12,
    herbs: 4,
    ore: 0,
  },
  {
    id: "cart",
    name: "パン屋の荷馬車",
    kind: "護衛" as Kind,
    region: "木漏れ日の街道",
    desc: "焼きたてのパンを隣町へ。つまみ食いは厳禁。",
    tier: 1,
    need: 34,
    seconds: 90,
    gold: 52,
    xp: 18,
    herbs: 1,
    ore: 2,
  },
  {
    id: "slime",
    name: "畑を荒らすスライム",
    kind: "討伐" as Kind,
    region: "クローバー平原",
    desc: "ぷるぷるの侵入者から、村の畑を守ろう。",
    tier: 1,
    need: 38,
    seconds: 120,
    gold: 70,
    xp: 24,
    herbs: 0,
    ore: 4,
  },
  {
    id: "crystal",
    name: "青晶石の採掘",
    kind: "採取" as Kind,
    region: "青く輝く洞窟",
    desc: "崩れやすい洞窟で、魔力を宿す鉱石を探す。",
    tier: 2,
    need: 85,
    seconds: 240,
    gold: 180,
    xp: 60,
    herbs: 2,
    ore: 12,
  },
  {
    id: "pilgrim",
    name: "星見の巡礼団",
    kind: "護衛" as Kind,
    region: "霧の山道",
    desc: "道に迷った巡礼者たちを、山頂の祠まで。",
    tier: 2,
    need: 90,
    seconds: 300,
    gold: 240,
    xp: 78,
    herbs: 8,
    ore: 8,
  },
  {
    id: "wolf",
    name: "霧狼の群れ",
    kind: "討伐" as Kind,
    region: "銀霧の渓谷",
    desc: "深い霧から聞こえる遠吠え。連携が試される。",
    tier: 2,
    need: 100,
    seconds: 360,
    gold: 310,
    xp: 95,
    herbs: 3,
    ore: 16,
  },
  {
    id: "blossom",
    name: "千年樹の花",
    kind: "採取" as Kind,
    region: "忘れられた樹海",
    desc: "千年に一度咲く花を求め、森の奥へ。",
    tier: 3,
    need: 170,
    seconds: 600,
    gold: 620,
    xp: 180,
    herbs: 35,
    ore: 10,
  },
  {
    id: "royal",
    name: "王女の秘密の旅",
    kind: "護衛" as Kind,
    region: "星降りの峠",
    desc: "お忍びの王女を護衛して、星の祭りへ。",
    tier: 3,
    need: 185,
    seconds: 720,
    gold: 800,
    xp: 230,
    herbs: 20,
    ore: 24,
  },
  {
    id: "dragon",
    name: "古塔の星喰い竜",
    kind: "討伐" as Kind,
    region: "星灯りの古塔",
    desc: "消えかけた星の灯りを取り戻す、旅団の大冒険。",
    tier: 3,
    need: 210,
    seconds: 900,
    gold: 1200,
    xp: 320,
    herbs: 15,
    ore: 45,
  },
];
export type Quest = (typeof quests)[number];
export const bonds = [
  {
    ids: ["aria", "leon"],
    name: "幼なじみの約束",
    bonus: 10,
    lines: ["アリア「こっちが近道！ たぶん！」", "レオン「その『たぶん』は何回目だ？」"],
  },
  {
    ids: ["mira", "finn"],
    name: "お目付け役と悪戯っ子",
    bonus: 10,
    lines: ["フィン「この宝箱、ちょっと開けても…」", "ミラ「帰ったらお説教とお茶ね。」"],
  },
  {
    ids: ["garr", "mira"],
    name: "やさしい守り手",
    bonus: 14,
    lines: [
      "ガル「みんなの荷物は、俺が持とう。」",
      "ミラ「貴方はみんなの荷物を、私はみんなの元気を。」",
    ],
  },
  {
    ids: ["luna", "noel"],
    name: "星と詩の物語",
    bonus: 16,
    lines: ["ルナ「星の声、聞こえる？」", "ノエル「ああ。次の歌が生まれそうだ。」"],
  },
  {
    ids: ["aria", "poppy"],
    name: "森のおすそわけ",
    bonus: 14,
    lines: ["ポピー「これ、飲めば空を飛べるかも！」", "アリア「かも、で飲ませないでよ！」"],
  },
];
export const level = (xp: number) => Math.min(50, 1 + Math.floor(Math.sqrt(xp / 30)));
